### ISSUE TITLE
util.AddModelAnimations( string base_mdl, string animations_mdl )

### ISSUE THREAD

**Issue by Tripperful** [Facepunch/garrysmod-requests#980] opened 2017-06-17 13:58 UTC
**Backstory of this request**

Hey there. I've been thinking a lot about how would it be possible to create and use additional animations as separate mdl files and use them for already existing models.

Valve enabled us to create mdl files with animations (like "models/m_anm.mdl" for players, for example) and include them in other mdls (the actual models that we want to play animations on), this has many benefits, since we don't have to recreate/duplicate animations that we want to be the same for several different models.

Though this tool is very useful, it can only be used when the model is compiled, meaning that we will be able to create additional models with animations to be used, but we won't be able to include them in already existing models, even though included model in mdl file is just a filename of the mdl we want to include animations from in the very end of the file.

This is such a pity that we are unable to add custom animations for already existing models in a good way without recompiling the model and making players download it, even though it is the same file with just one more include inside of it.

**The actual request**

Probably it is possible to find a way to tweak the function that loads an mdl file and caches it (the function that reads the model includes in mdl data structure would be a good place) to not only add those models from mdl file to includes list, but also add includes from a custom model includes table that can be added and processed the same way as the includes that were read from the mdl itself.

**What it will give to players and developers**
- Developers will be able to create custom animations sets for already existing hl2 models or what more for their servers/addons/gamemodes/whatever
- Developers will not have to recompile already existing models to add more animations to them
- Players will only have to download the mdl file with new animations, reducing their load time in such cases
- Developers and players will be happy to be able to create and see new custom animations for players and other stuff, achieved in a natural and optimized way, without manual bone manipulation, invisible skeleton bone merging and other shit

**How it will work**
- Gmod has some special table where it stores a structure that logically looks like
```Lua
{
    some_model_filename = { 
        some_anims_filename, 
        some_other_anims__filename, 
    }, 
    some_other_model = 
    ... 
}
```
- When the game loads an mdl and processes it's includes, it accesses this table
- The function checks if there are additional includes for this model in the table, if so, it processes them the same way as regular mdl includes
- Developers have a special function bind to add entries to this custom mdl includes table (see request name)
- When we call this util function, we'll have to flush and cache the model again if it was already cached in memory
- Using this function after the game is likely to cause crashes, so we should probably allow using it in early hooks

**Comment by robotboy655** [comment] 2017-06-17 15:01
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/230

**Closed by robotboy655** 2017-06-17 15:01 UTC
Labels: duplicate
