### ISSUE TITLE
Allow :SetDSP() to be used with IGModAudioChannel

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-requests#2317] opened 2024-03-13 20:33 UTC
Title says it all, I do not think that IGModAudioChannel allows you to use SetDSP on its snd entity.

Would be nice to use because sound.PlayFile() has much more in-depth capabilities VS CreateSound()

**Comment by robotboy655** [comment] 2024-03-14 13:50
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/2301

**Closed by robotboy655** 2024-03-14 13:50 UTC
