### ISSUE TITLE
Add more arguments to ShutDown hook

### ISSUE THREAD

**Issue by Andrew-Eathan** [Facepunch/garrysmod-requests#1978] opened 2022-06-12 13:41 UTC
### Details
add more arguments to the ShutDown hook specifying if the server is shutting down or changing maps

**Comment by robotboy655** [comment] 2023-11-03 15:21
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1221

**Closed by robotboy655** 2023-11-03 15:21 UTC
