### ISSUE TITLE
Add a hook to detect player ammo change

### ISSUE THREAD

**Issue by Tripperful** [Facepunch/garrysmod-requests#1305] opened 2019-03-03 17:45 UTC
Something like GM:OnPlayerAmmoChanged( ply, type, amount ) would be perfect, even better if you could return something from there to prevent ammo change or override it. It is currently impossible, of course you can hook something like FireBullets but not all custom weapons that take ammo actually fire bullets

**Comment by Tripperful** [comment] 2019-03-03 17:50
And of course it should be called when you both lose or gain ammo or when it's manually changed via code, with negative values for when you lose it and positive values for when you take some

**Comment by robotboy655** [comment] 2019-03-03 18:21
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1131

**Closed by robotboy655** 2019-03-03 18:21 UTC
