### ISSUE TITLE
Create a binding allowing addons to spawn/modify ai_hint entities

### ISSUE THREAD

**Issue by DimasDSF** [Facepunch/garrysmod-requests#2497] opened 2024-10-17 15:59 UTC
### Details

Currently there are many addons available that allow modifying the nodegraph
but `.ain` file nodegraph does not store any info on hint entities making it impossible to create a fully functional nodegraph for engine NPCs. Such as jump overrides and ActBusy hints

Game code has a console command at https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_hint.cpp#L1651 for creating an `ai_hint` entity and it seems to affect NPCs right after the hint is created,
however its a debug command that drops the hint at the calling players EyePosition,
it uses a `HintNodeData` structure to spawn the hint, that has:
- strEntityName
- vecPosition
- nHintType
- strGroup
- iDisabled
- iszActivityName
- fIgnoreFacing
- minState
- maxState
The hint itself has a keyvalue for the hints FoV but it can already be accessed.

it would be nice if a lua method was created for spawning an `ai_hint` using parameters in `HintNodeData` 
or a way to construct a `HintNodeData` in lua (might be useful for editing an already existing `ai_hint` if it can be retrieved from one) and then use it to spawn an `ai_hint` using `CAI_HintManager::CreateHint`

**Comment by robotboy655** [comment] 2024-10-17 16:07
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/2129

**Closed by robotboy655** 2024-10-17 16:07 UTC

**Comment by DimasDSF** [comment] 2024-10-17 16:33
Sorry to be a nuisance, but #2129 talks about reading the nodegraph and getting node data from it (that is an already solved issue). 
This one is about creating and modifying the `ai_hint` entities that exist after the map is loaded not the `info_hint/info_node_hint` hammer/nodegraph counterparts.
Once again I'll understand if this is rejected due to it being something that would rarely be used, but just wanted to clarify.

**Comment by robotboy655** [comment] 2024-10-17 17:02
As per the valve developer wiki: https://developer.valvesoftware.com/wiki/Ai_hint

> ai_hint is a point entity. When an info_hint, info_node_hint or info_node_air_hint has a Hint (hinttype) other than None, this entity will be created in place of it and retain much of the former entity's data, including targetname and IO.

So, can't you already create this entity anyway including all the specialized data via creating `info_node_(air_)hint` entities like normally intended by the engine?

**Comment by DimasDSF** [comment] 2024-10-17 17:16
Yes, ai_hint entities are created from hint related info_nodes in the .bsp file placed in hammer when the world spawns them in ( https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/ai_initutils.cpp#L235 ), from what I remember spawning info_node* entities has no effect in game (I will try once again and check), with this though - one could easily be created mid-game.

**Comment by robotboy655** [comment] 2024-10-17 17:25
Both the concommand and those entities use the exact same function to create the `ai_hint` entity. You just have to setup the entity correctly and call `Spawn()` on it.

**Comment by DimasDSF** [comment] 2024-10-18 17:42
Got it to work with the only downside being that the console command called `Activate` on the newly created `ai_hint` while the node `Spawn` method does not and since there is no way to get the created hint from calling that I had to activate every single ai_hint on the map (would probably be better to find entities in a small radius around the new node position and filter them by classname).
While testing I got to work on the jump hint and the nodegraph editing and figured out a way to specifically create jump links in the nodegraph too, so I'm pretty happy with that. Thanks for pointing me in the right direction.

**Comment by robotboy655** [comment] 2024-10-18 18:23
The `ai_hint` entity should take the `tagetname` from the parent entity you create. You should be able to get the correct `ai_hint` using that.

https://wiki.facepunch.com/gmod/ents.FindByName

or search all `ai_hint` after you done spawning them, and check the name.
