### ISSUE TITLE
Add allowlist/denylist field to Trace structure

### ISSUE THREAD

**Issue by NoSharp** [Facepunch/garrysmod-requests#2214] opened 2023-11-17 13:47 UTC
### Details
Add an inverse of the filter field, to act as a allowlist rather than a deny list.

https://wiki.facepunch.com/gmod/Structures/Trace

**Comment by Kefta** [comment] 2023-11-17 15:00
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/937

**Closed** 2023-11-17 15:22 UTC
