### ISSUE TITLE
Add Baked ambient occlusion into vrad and more

### ISSUE THREAD

**Issue by Unusuario2** [Facepunch/garrysmod-requests#2347] opened 2024-03-31 20:31 UTC
### Details
Because there is no plans (aparently) to implement the AO into vrad i could help to make that possible. How?
So i have the code of slammin tools (vbsp,vvis,vrad[SP/MP]) i could provide a private repo with contains this code [github]
What about the permission of slammin? If you aprove this i will ask him and provide proof of his permission.

Becouse GMOD is a license source engine game has access to full src code and **i belive** to other repos of valve games, such us portal or csgo so it woundnt be a problem to use this code into GMOD. 
The benefits are having all the features of SLT which is constantly requested by the community.

And also you might ask your self why not use stock STL? Simple becouse they are not 64 bits and if you raise up some of the limits in the compiler such us `#define MAX_MAP_DISPINFO				16384	` they will crash and there is no easy fix for that.

Ideally this would have all the features of SLT

**Comment by robotboy655** [comment] 2024-04-01 06:23
This sounds a bit incoherent, so I am just gonna close this as a duplicate of your own previous report https://github.com/Facepunch/garrysmod-requests/issues/2264

**Closed by robotboy655** 2024-04-01 06:23 UTC

**Comment by Unusuario2** [comment] 2024-04-01 14:25
The point was that moving all the code containing the csgo features to the GMOD branch is difficult and very tedious. So to facilitate this process and not take so long, if you want it, I or Slammin tools (if he gives me permission), I (or he) could provide you with the code to make this a reality (vbsp,vvis,vrad). 
https://web.archive.org/web/20190611221800/https://forum.facepunch.com/dev/bvenk/Slammin-Source-map-tools/
https://developer.valvesoftware.com/wiki/Slammin%27_Source_Map_Tools
