### ISSUE TITLE
Implement universal binary stream/buffer class

### ISSUE THREAD

**Issue by Tripperful** [Facepunch/garrysmod-requests#1324] opened 2019-04-11 06:54 UTC
I think it's the best to explain it in code:

**Let's suppose we have Boo object 'class' with the following structure:**
```Lua
local boo1 = {
	intVal = -3,
	uintVal = 35,
	stringVal = "test",
}
```

**What we do now:**

```Lua
function net.WriteBoo( boo )
	net.WriteInt( boo.intVal )
	net.WriteUInt( boo.uintVal, 32 )
	net.WriteString( boo.stringVal )
end

function net.ReadBoo()
	return {
		intVal = net.ReadInt(),
		uintVal = net.ReadUInt( 32 ),
		stringVal = net.ReadString(),
	}
end

local file = FindMetaTable( "File" )

function file:WriteBoo( boo )
	-- Something similar to net implementation
end

function file:ReadBoo()
	-- Something similar to net implementation
end

-- And any other data APIs implementations which all do almost the same thing

-- Usage:
net.WriteBoo( boo1 )
boo1 = net.ReadBoo()
f:WriteBoo( boo1 )
boo1 = f:ReadBoo()
```

**What we can do:**

```Lua
local stream = FindMetaTable( "BinaryStream" )

function stream:WriteBoo( boo )
	self:WriteInt( boo.intVal )
	self:WriteUInt( boo.uintVal )
	self:WriteString( boo.stringVal )
end

function stream:ReadBoo()
	return {
		intVal = self:ReadInt(),
		uintVal = self:ReadUInt(),
		stringVal = self:ReadString(),
	}
end

-- Usage:
local stream = BinaryStream()
stream:WriteBoo( boo1 )

net.WriteStream( stream )
f:WriteStream( stream ) -- or stream:Save( "filename.dat" )

local boo1 = net.ReadStream():ReadBoo()
local boo1 = f:ReadStream():ReadBoo() -- or BinaryStream():ReadFromFile( "filename.dat" )
```

Imagine Boo being something more complex than 3 variables and changing its structure at some point, how many read/write functions you'd need to modify?

Imagine these universal binary streams being able to read/write any primitive types and maybe even tables (like net library does), being able to binarize any data structures for storage/transmission, adding optional compression when writing those to files/net would be so helpful.

This can be done in lua, ofc (and that's what I actually do now with my datamodel library), representing binary data in strings but with so much unnecessary overhead, implementing such class in C++ would be much more beneficial.

**Comment by Kefta** [comment] 2019-04-11 07:01
Partial duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1154.

**Comment by Tripperful** [comment] 2019-04-11 07:14
Yeah I saw it @Kefta 
, just thought that maybe explaining it better would at least increase the chance of Rubat implementing this by 0.1% huh and maybe more community members would understand how such a stream would be used

**Comment by thegrb93** [comment] 2019-04-11 14:59
This would fix the main woe of advdupe2.

**Comment by robotboy655** [comment] 2019-04-11 16:03
This is as mentioned a duplicate of #1154

**Closed by robotboy655** 2019-04-11 16:03 UTC

**Comment by Tripperful** [comment] 2019-04-12 12:17
Please...
