### ISSUE TITLE
Pls add a hook 

### ISSUE THREAD

**Issue by plexx-0w0** [Facepunch/garrysmod-requests#1647] opened 2020-07-04 18:37 UTC
Add a hook like https://wiki.facepunch.com/gmod/GM:PlayerInitialSpawn but the hook is only called when the player has fully loaded into the game. (after the starting lua screen) bc currently we have to do shitty workarounds to get a function called at the right time (when the player is fully loaded and spawned in) thx i would highly appreceate the effort :)

btw sry for my bad english

**Comment by robotboy655** [comment] 2020-07-04 18:50
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/718

**Closed by robotboy655** 2020-07-04 18:50 UTC
