### ISSUE TITLE
Backport point_viewproxy

### ISSUE THREAD

**Issue by URAKOLOUY5** [Facepunch/garrysmod-requests#2517] opened 2024-10-31 14:07 UTC
### Details
https://developer.valvesoftware.com/wiki/Point_viewproxy

It's just serverside entity same as `point_viewcontrol` and can be useful in more than just Portal 2

**Comment by robotboy655** [comment] 2024-10-31 15:43
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/2281

Please use the search feature before posting here.

**Closed by robotboy655** 2024-10-31 15:43 UTC
