### ISSUE TITLE
Give the server browser genres

### ISSUE THREAD

**Issue by ottworks** [Facepunch/garrysmod-requests#459] opened 2015-04-13 04:36 UTC
As detailed in [this post](http://facepunch.com/showthread.php?t=1459233&p=47495519&viewfull=1#post47495519) by TylerB:

> I still think that genres in the server menu would be a good idea for filtering down gamemodes.
> 
> e.g.
> 
> All
> - all servers, no filtering.
> 
> Sandbox
> - Sandbox
> - Build To Kill
> - Sledbuild?
> 
> RP
> - DarkRP
> - HL2RP
> - BuildRP
> - etc
> 
> PvP
> - TTT
> - GunGaym
> - Murder
> - etc
> 
> Minigames
> - EFT
> - Fretta
>   etc
> 
> Other
> - uncategorized?
> 
> it would at least make the lesser known servers not off the bottom of the page, right?

...

> It'd be set the same way the gamemodes are set now.
> 
> GM.Genre = "RP" or something
> 
> if it's not a valid genre (as determined by the server list?) it'll fall into uncategorized

**Comment by JoshuaDoes** [comment] 2015-04-13 06:28
This would be really nice. But for it to work out the way you expect, each individual gamemode would have to have it's category in the addon itself, not the server listings. And with this in mind, addons could potentially abuse it and add many different unneeded categories based on how you suggested it to work, as being able to use any valid alphanumeral character in the string for the Genre variable.

Sorry if I popped the bubble :D I just wanted to show the different sides of things :P 
~JoshuaDoes

**Comment by DaaOtt** [comment] 2015-04-13 06:32
There would be a whitelist. GM.Genre would be set in the server tags (like how gamemodes already are) and the client would choose how to interpret those tags. Everything that's not on the whitelist would be put on the bottom or in the "other" genre.

**Comment by DaaOtt** [comment] 2015-04-13 06:34
>each individual gamemode would have to have it's category in the addon itself, not the server listings. 

Care to elaborate?

**Comment by JoshuaDoes** [comment] 2015-04-13 06:36
Every addon that features a gamemode would have to specify which category it belongs to. From the way I interpreted your example, it would use any string found in the GM.Genre variable. Therefore, not only would --
  GM.Genre = "Roleplay"
work, but someone could also do this:
  GM.Genre = "Spam1203928" (Just an example. There could be word filters, but you should get the point.)

**Comment by DaaOtt** [comment] 2015-04-13 06:37
And your point is?

**Comment by JoshuaDoes** [comment] 2015-04-13 06:37
I'm just trying to show how one could abuse it if it were setup like that. No harm intended

**Comment by wiox** [comment] 2015-04-13 06:38
> There would be a whitelist

**Comment by DaaOtt** [comment] 2015-04-13 06:39
There's really no room for abuse. Anything not on the whitelist just gets dumped in the "other" section.

**Comment by JoshuaDoes** [comment] 2015-04-13 06:40
The better way to do it is assign each allowed genre to a number, ex. 0 = Uncategorized, 1 = Roleplay, 2 = Scenery, 3 = Fun, 4 = PVP, etc
And it would be assigned like GM.Genre = 0, and if a number is specified that is not assigned, that would be up to the programmer to choose whether or not to put it in uncategorized or just not list it at all

**Comment by JoshuaDoes** [comment] 2015-04-13 06:40
But yeah, it would probably just be uncategorized

**Comment by wiox** [comment] 2015-04-13 06:41
How the hell is using arbitrary numbers better than a human-readable string? I feel like you're just trying to find holes in a semi-decent idea.

**Comment by DaaOtt** [comment] 2015-04-13 06:41
Or better yet use an enum. I like strings though, there's more room for custom filters.

**Comment by JoshuaDoes** [comment] 2015-04-13 06:44
wiox: I don't mean to sound like I'm ruining an idea. It's just what I'm used to, sorry :/

**Comment by TylerB260** [comment] 2015-04-13 11:59
or, adding on to my original post, if the genre isn't in the whitelist, perhaps it could be plopped into the other section, which would list all of the other genres?

**Comment by TheFreeman193** [comment] 2015-04-13 14:49
I'm all for this idea. I reckon it should be case insensitive and with some tolerance, though; e.g. *RP*, *Roleplay*.

**Comment by AnonTakesOver** [comment] 2015-04-14 00:33
This is a good idea, but what's stopping someone changing their genre to something else? Like changing an rp to sandbox etc.
I know it wouldn't be a massive deal but if lots of people do it, than it is.

However, the main suspects for this will be rp, so i reckon you should check the gamemode name to see if it contains "rp" in it, and force it's genre to Roleplay

**Comment by DaaOtt** [comment] 2015-04-14 00:34
The ratings. Miscategorizing your gamemode will only alienate you from the crowd you're catering to.

**Comment by DaaOtt** [comment] 2015-04-25 01:16
Any official word on this?

**Comment by SwadicalRag** [comment] 2015-04-25 02:01
Also, something semi related, are we looking into changing the server priority calculations? I saw another issue/request about it, looks like it got buried.

For reference, just in case: 
```javascript
	data.recommended = data.ping;
	if ( !data.hasmap ) data.recommended += 20; // We don't have that map
	if ( data.players == 0 ) data.recommended += 100; // Server is empty
	if ( data.players == data.maxplayers ) data.recommended += 75; // Server is full
	if ( data.pass ) data.recommended += 300; // If we can't join it, don't put it to the top
```
(the higher data.recommended is, the lower the server is on the serverlist)

**Comment by DaaOtt** [comment] 2015-04-25 02:03
That would be https://github.com/garrynewman/garrysmod/pull/815.

**Comment by TylerB260** [comment] 2015-04-25 02:18
Instead of having a moderated list of genres, perhaps we could just list the most populated genres?

**Comment by DaaOtt** [comment] 2015-04-25 02:22
That would introduce the same issue that gamemodes have.

**Comment by TylerB260** [comment] 2015-04-25 02:24
How though? There's not going to be 20+ genres.

**Comment by DaaOtt** [comment] 2015-04-25 02:28
I misunderstood.

**Comment by DingoDown** [comment] 2020-11-28 20:44
Five years later and we're still using a shitty server browser...

**Comment by robotboy655** [comment] 2021-03-18 17:17
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1593

**Closed by robotboy655** 2021-03-18 17:17 UTC
