### ISSUE TITLE
Improve scaling of UI for resolutions above 1440p

### ISSUE THREAD

**Issue by wolfestridershooter** [Facepunch/garrysmod-requests#1847] opened 2021-04-06 17:09 UTC
### Details:
Text is borderline unreadable on screens above 1440p and navigating UI is just overall an uncomfortable experience. It would really be nice to have the UI as large as it appears at 1080p.

(Not sure if this has been requested before but I couldn't find a duplicate)

### Example of tiny text:
![image](https://user-images.githubusercontent.com/47306808/113750876-4d119680-96d9-11eb-83a3-0fdfe930f7c0.png)

**Comment by MARK2580** [comment] 2021-04-19 20:04
This is a problem with any Source Engine of the game, this interface was created back in 2004 (when the resolution of 1920 × 1080 was something overwhelming) and has never changed during all this time. I doubt that the UI of the engine itself is generally possible to somehow increase depending on the resolution. Probably only the Garry's Mod interface itself.

**Comment by jorjic** [comment] 2022-12-10 04:03
The game UI comes mostly in two pieces: the Chromium main menu and the legacy Source engine VGUI components.

Since the main menu uses HTML+CSS+JS, it should be easy to fix for UI scaling. I'm not a capable web developer, so I don't know how to do that. However, I was able to get very cheap 4K scaling by pushing the browser zoom to 200%. I can't post a screenshot, but it looks almost identical to 1920x1080.
```js
// Stick this in html/menu.html
<script type="javascript">
	$(document).ready(function () {
                var scale = window.screen.width / 1920;
		document.body.style.zoom = toString(scale * 100) + "%";
	});
</script>
```

VGUI is harder to fix. In garrysmod/resources/ there are several .res files that control font sizes and colors. `SourceScheme.res` has an entry for the ConsoleText font which is predictably used in the console. I can change the font size to make it readable at 4K, but not without changing it for lower resolution also. Fonts defined in the .res files have a `yres` property that controls what font/size/effects are used at various scales. I can't make it work for ConsoleText, but it works well for TargetID, which is the font used when looking at a player. Maybe the Facepunch devs can make that work somehow.
```
		"TargetID"
		{
...
			"5"
			{
				"name"		"Verdana"
				"tall"		"22"
				"weight"	"700"
                                // yres must be changed down from 1200-10000 or the next one does not take effect
				"yres"		"1200 2159"
				"dropshadow"	"1"
			}
			"6"
			{
				"name"		"Verdana"
				"tall"		"34"
				"weight"	"700"
                                // double the font size (from 1080) when screen height is 2160 or above
				"yres"		"2160 10000"
				"dropshadow"	"1"
			}
		}
```

I can't find any good way to scale VGUI panels up well.

**Comment by robotboy655** [comment] 2022-12-10 12:52
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5123 and probably others

**Closed by robotboy655** 2022-12-10 12:52 UTC
