### ISSUE TITLE
Phongexponent halfvector from CS:GO

### ISSUE THREAD

**Issue by One-Trick-Viper** [Facepunch/garrysmod-requests#2101] opened 2023-06-15 22:04 UTC
I don't want to clog up the #next-update channel too much about this request, so I'll just put it here where it's supposed to be.

Since we're getting stuff from CS:GO's branch, the halfvector valve has added to the phongexponent calculation will do **wonders** for phong rendering. As it is now, viewing angle isn't properly taken into account for calculating the exponent. CS:GO fixed this with the halfvector (as far as I am aware of, if not, feel free to correct me).

Here are some examples to show what I mean with this:

Garry's Mod phongexponent value of 30 at this grazing angle:
![image](https://github.com/Facepunch/garrysmod-requests/assets/29631812/af41d00d-5258-4b28-8364-bd4373eadd93)

Counter-Strike: Global Offensive phongexponent value of 30 at the same grazing angle:
![image](https://github.com/Facepunch/garrysmod-requests/assets/29631812/59de2372-4063-4a29-a75c-ea088b020247)

And here is an example with just simple $phongboost instead of $phongalbedoboost:

Garry's Mod:
![image](https://github.com/Facepunch/garrysmod-requests/assets/29631812/ca8be425-f577-45f1-870c-c56061412bcb)

Counter-Strike: Global Offensive:
![image](https://github.com/Facepunch/garrysmod-requests/assets/29631812/c4f32f37-7cee-4c19-bfa8-c53fda349540)

Now, I am not sure how much this will affect current materials made for Garry's Mod, but I would absolutely appreciate your input on this specifically and if it's feasible.

**Comment by robotboy655** [comment] 2023-06-15 22:39
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1839

**Closed by robotboy655** 2023-06-15 22:39 UTC
Labels: Shaders
