### ISSUE TITLE
ENT:GetActivityIDFromName and ENT:GetActivityNameFromID

### ISSUE THREAD

**Issue by Dragoteryx** [Facepunch/garrysmod-requests#1383] opened 2019-08-08 23:36 UTC
When importing a model from another Source game sometimes (most of the time) it uses activities that aren't defined in the ACT enumerations. The function `ENT:GetSequenceActivityName` is currently the only function that lets us get the name of the activity, but I suppose this is because the `mstudioseqdesc_t` struct has that info.

I was wondering if it was possible to add functions to get the activity ID of activities that are not defined in the ACT enums, and if it is possible the opposite might be useful too.

For example, the Witch from L4D2 has a sequence called `Idle_Standing_Crying`, which uses the activity `ACT_TERROR_WITCH_WANDER_IDLE`, which isn't defined in the ACT enums. Using this function we could do something like this:
```lua
-- in that example, self is a nextbot
local actId = self:GetActivityIDFromName("ACT_TERROR_WITCH_WANDER_IDLE")
self:StartActivity(actId)
```

**Comment by robotboy655** [comment] 2019-08-09 11:16
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/950

https://github.com/Facepunch/garrysmod-requests/issues/1069
https://github.com/Facepunch/garrysmod-requests/issues/121

**Closed by robotboy655** 2019-08-09 11:16 UTC
