### ISSUE TITLE
Hook OnNPCKilled Client side

### ISSUE THREAD

**Issue by Goldermor** [Facepunch/garrysmod-requests#2013] opened 2022-08-18 09:19 UTC
is it possible for us to have this hook on the client? I'm asking because I think it will help fix the localization error for killbar, because all strings that have localization appears as untranslated one.

if that's not the case, then what can fix it?

![unknown](https://user-images.githubusercontent.com/77431249/185358917-b99f04f7-72b0-4c24-b7df-db42ed4a214c.png)

**Comment by robotboy655** [comment] 2022-08-18 11:16
Localization for kill names already works. All base NPCs use it. It seems that whatever addon NPC that is - it simply did not include any localization.

Similar/dupe of https://github.com/Facepunch/garrysmod-issues/issues/5301

**Closed by robotboy655** 2022-08-18 11:16 UTC

**Comment by Goldermor** [comment] 2022-08-18 12:57
what is meant by "base NPCs"? what if it's a nextbot or any other entity that run OnNPCKilled hook?
![s](https://user-images.githubusercontent.com/77431249/185399915-4c7f55c9-b6ae-43b4-bf25-12900c1be2f6.png)
everything was done correctly, but the name is still untranslated in the killbar

**Comment by robotboy655** [comment] 2022-08-18 14:46
"Base NPCs" means all NPCs that come with the base game by default. They all use the localization system. It doesn't matter what class or type of entity they are, that difference cannot affect the localization system.

It's important to notice that the killfeed will use `#classname` of the entity. It will completely ignore whatever you put into `Name` of your `list.Set`. So whatever you are doing is non standard and that's where your issue must be. (like having trailing/leading whitespace in the string you pass into killfeed by whatever means for example)
