### ISSUE TITLE
Custom Closed Captions support from a file

### ISSUE THREAD

**Issue by Goldermor** [Facepunch/garrysmod-requests#2136] opened 2023-07-18 16:11 UTC
it would be really useful to get custom сlosed сaptions support.
i think they can be used in the same way as .properties files, so we can just put .dat files to resource\localization\%language% and gmod will load them.

**Comment by robotboy655** [comment] 2023-07-18 16:14
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/2024

Also related https://github.com/Facepunch/garrysmod-requests/issues/1745

**Comment by robotboy655** [comment] 2024-12-13 14:09
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1994

**Closed by robotboy655** 2024-12-13 14:09 UTC
