### ISSUE TITLE
system.CurrentInputLanguage()

### ISSUE THREAD

**Issue by matiz128** [Facepunch/garrysmod-requests#2287] opened 2024-02-11 15:12 UTC
### Details
Function returnы selected keyboard layout language

**Comment by robotboy655** [comment] 2024-02-11 15:17
I don't see a legitimate use for this.

**Comment by matiz128** [comment] 2024-02-11 15:26
Change language id style for dtextentry

**Comment by klen-list** [comment] 2024-02-29 10:16
Duplicate of #1053

**Closed** 2024-02-29 12:17 UTC
