### ISSUE TITLE
let Entity:EmitSound take a CRecipientFilter

### ISSUE THREAD

**Issue by mgetJane** [Facepunch/garrysmod-requests#2025] opened 2022-10-07 03:01 UTC
this is something that the source engine can already do but gmod doesnt let you take advantage of because the emitsound functions are incredibly neutered for some reason

map optimisations can cause important sounds to not be received by clients at all (like in ttt there are many places in maps where you can't hear a c4 beeping through the wall right next to you)
and to get around this you'd need to use the net library just to literally re-implement something that the engine can already do

another thing that would be great is if it could take a Vector for where the sound gets played from (another thing the source engine can already do but gmod doesnt let you take advantage of) so you don't have to use dummy ents or sound.Play which is incredibly limited

**Comment by Kefta** [comment] 2022-10-07 05:33
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/520

**Comment by robotboy655** [comment] 2022-10-07 10:39
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/520

**Closed by robotboy655** 2022-10-07 10:39 UTC
