### ISSUE TITLE
Add option to uploading files with type HTML,CSS and JS to workshop

### ISSUE THREAD

**Issue by Likanin555** [Facepunch/garrysmod-requests#1189] opened 2018-07-07 15:19 UTC
Because i want to publish custom main menu but file ,,Not allowed by whitelist".

Thanks.

**Comment by CornerPin** [comment] 2018-07-07 15:32
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1156

**Closed** 2018-07-09 13:09 UTC
