### ISSUE TITLE
Provide a platform for the community to submit translations for the files in the resource folder, such as garrysmod_english.txt, and other files in the resource/language/ folder

### ISSUE THREAD

**Issue by IBRS-4Ever** [Facepunch/garrysmod-requests#2486] opened 2024-09-30 06:46 UTC
### Details

![image](https://github.com/user-attachments/assets/a06f016f-347a-4a1a-abfe-1b9b26c85938)
![image](https://github.com/user-attachments/assets/db5cedde-bc52-4be3-b70f-66d4d706d99d)

About Close Captions, is it possible for community to provide translation as well? So that we can fix incorrect translations, improve translations, etc.

**Comment by robotboy655** [comment] 2024-09-30 11:47
Effectively duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2580

**Closed by robotboy655** 2024-09-30 11:47 UTC
Labels: Content
