### ISSUE TITLE
util.Base64Decode

### ISSUE THREAD

**Issue by edgarasf123** [Facepunch/garrysmod-requests#1076] opened 2018-01-05 07:37 UTC
Add `util.Base64Decode`. Function to encode base64 exist(`util.Base64Encode`), but no function exist to decode base64.

**Comment by robotboy655** [comment] 2018-01-05 07:37
If only you'd bother to search first.

Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/109

**Closed by robotboy655** 2018-01-05 07:37 UTC

**Comment by edgarasf123** [comment] 2018-01-05 07:39
I did look it up, maybe I made grammar mistake or went blind or something. Sorry.
