### ISSUE TITLE
Lua equivalent of $includemodel

### ISSUE THREAD

**Issue by TiberiumFusion** [Facepunch/garrysmod-requests#1775] opened 2020-12-31 08:34 UTC
### Request
The title pretty much sums it up. There should be a way to append one model's sequences to another at runtime. Or, preferably, a way to copy/delete specific sequences to/from a different model.

The valve wiki says: *"The $includemodel QC command is used to add an MDL file that this model will include at run-time. All new sequences and animations will be appended to the model."*

So surely this kind of request is possible. And maybe even straightforward to implement...? I hope?

### Reasoning
**Rebuilding assets is not always an option.** In fact, I have found myself walled and simply unable to meet requirements due to this limitation more often than I would like. Creating dynamically served and assembled models is simply impossible right now. There's a lot of high-quality addon concepts that would be enabled by adding the ability to $includemodel with Lua. Imagine modular SWEPs or playermodels that can be easily personalized by the user and are actually relatively performant.

There is a ridiculous amount of customization and modification available to everything in gmod these days - except animations. Player expectations continue to grow and we're running out of new ways to feed that hunger. The simple ability to add/remove sequences at runtime would fill a major hole and enable novel addons that are just plain impossible right now.

**Comment by Kefta** [comment] 2020-12-31 08:41
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/230

**Closed by Kefta** 2020-12-31 08:41 UTC
