### ISSUE TITLE
Make it possible to tell if LocalPlayer is connected to SourceTV (27020) or not

### ISSUE THREAD

**Issue by Glebux** [Facepunch/garrysmod-requests#2524] opened 2024-11-06 16:13 UTC
### Details
Add a function like `engine.IsPlayingDemo()` that returns true if the client is spectating through SourceTV, easy.

**Comment by robotboy655** [comment] 2024-11-06 17:52
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/2298

**Closed by robotboy655** 2024-11-06 17:52 UTC
