### ISSUE TITLE
include function return value of file

### ISSUE THREAD

**Issue by mechanicalmind** [Facepunch/garrysmod-requests#602] opened 2015-11-30 09:17 UTC
The include function should return the value returned by the file. This is common practice in regular Lua.

multiply.lua
````lua
return function (a, b) return a * b end
````

init.lua
````
multiply = include("multiply.lua")
print(multiply(2, 5))
````

**Comment by Kefta** [comment] 2015-11-30 09:24
This is tied with the outdated module behaviour as well

**Comment by mechanicalmind** [comment] 2015-11-30 09:29
I'm not sure what you mean by that.

**Comment by robotboy655** [comment] 2015-11-30 12:57
Duplicate of #393

**Closed by robotboy655** 2015-11-30 12:57 UTC
