### ISSUE TITLE
Notify the client that the server is freezing or has crashed

### ISSUE THREAD

**Issue by Earu** [Facepunch/garrysmod-requests#1551] opened 2020-03-24 23:32 UTC
With a hook or something of the sort, it would be helpful for add-ons that try to process information or do special things when the server crashes or is freezing. 

Currently the only way to do this is to have the server send some kind of heartbeat every n seconds to the clients. So every time someone wants to deal with this case they have to create a new heartbeat logic, you can imagine that if lots of add-ons (granted unlikely) starts doing it, it would cause issues. This would also standardize how people deal with this case.

**Comment by Python1320** [comment] 2020-03-24 23:53
In the meantime you can check if the return values from engine.ServerFrameTime() have changed to detect if server is still sending messages.

**Comment by robotboy655** [comment] 2020-06-01 16:29
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/914

**Closed by robotboy655** 2020-06-01 16:29 UTC
