### ISSUE TITLE
HTTPReady hook

### ISSUE THREAD

**Issue by Doogls** [Facepunch/garrysmod-requests#2198] opened 2023-10-30 22:17 UTC
### Details
The HTTP module does not become available immediately from the server startup; usually HTTP is ready in the InitPostEntity hook, but in this hook, a large amount of time may pass from the moment the HTTP module is ready. I'd like to see a hook similar to "HTTPReady".
![изображение](https://github.com/Facepunch/garrysmod-requests/assets/47123206/ceb84e0e-13fd-47ea-829a-b6d252190e67)

**Comment by robotboy655** [comment] 2023-10-31 09:51
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1670

**Closed by robotboy655** 2023-10-31 09:51 UTC
