### ISSUE TITLE
Episodic NPC's features?

### ISSUE THREAD

**Issue by ALIEN31ITA** [Facepunch/garrysmod-requests#2415] opened 2024-06-17 15:45 UTC
i can't tell if these are already in Gmod? but it would be a cool feature to have
an example is Alyx getting blind by the flashlight, like literally here

https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/server/hl2/npc_alyx_episodic.cpp

**Comment by robotboy655** [comment] 2024-06-17 16:20
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5566

**Closed by robotboy655** 2024-06-17 16:20 UTC
Labels: Content
