### ISSUE TITLE
NPCMinBurst, NPCFireRate, etc. do nothing

### ISSUE THREAD

**Issue by HaodongMo** [Facepunch/garrysmod-requests#1378] opened 2019-08-05 16:16 UTC
According to weapon_base:
`-- These tell the NPC how to use the weapon
AccessorFunc( SWEP, "fNPCMinBurst",		"NPCMinBurst" )
AccessorFunc( SWEP, "fNPCMaxBurst",		"NPCMaxBurst" )
AccessorFunc( SWEP, "fNPCFireRate",		"NPCFireRate" )
AccessorFunc( SWEP, "fNPCMinRestTime",	"NPCMinRest" )
AccessorFunc( SWEP, "fNPCMaxRestTime",	"NPCMaxRest" )
`

The trouble is that they don't. To work around this, NPC weapon makers have to rely on tricks like burst timers, which just don't work very well or look very good. I'm requesting that these functions be properly implemented.

**Comment by robotboy655** [comment] 2019-08-05 16:27
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/933 and wrong repo.

**Closed by robotboy655** 2019-08-05 16:27 UTC
