### ISSUE TITLE
Don't print "Foobar called outside of command/prediction" if the function is pcall'd

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#888] opened 2016-12-28 05:25 UTC
With Player.GetCurrentCommand

**Comment by robotboy655** [comment] 2023-11-10 13:40
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2498

The crux of the issue is inability to detect if the current Lua call is inside a pcall.

**Closed by robotboy655** 2023-11-10 13:40 UTC
