### ISSUE TITLE
Allow HL2 Engine saving and loading in mutiplayer

### ISSUE THREAD

**Issue by wolfestridershooter** [Facepunch/garrysmod-requests#2381] opened 2024-05-07 05:57 UTC
### Why not use gmsave?
Because you can't save the state of any logic and brush entities with gmsave. This would be very useful for mutiplayer campaign mods because it would be a very significant step to getting changelevel2 to work in mutiplayer.

**Comment by robotboy655** [comment] 2024-05-15 16:58
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1783

**Closed by robotboy655** 2024-05-15 16:58 UTC
