### ISSUE TITLE
Allow NPCs to pick up SWEPs.

### ISSUE THREAD

**Issue by HaodongMo** [Facepunch/garrysmod-requests#1377] opened 2019-08-05 16:11 UTC
There is no way for default NPCs to be able to pick up SWEPs; however, from my cursory look at some outdated Source Engine NPC code, there is only one main hurdle, which is that it doesn't _say_ that it can be used. Not sure how much has changed but the C++ function **CanBePickedUpByNPCs( void )** seems to control whether or not a weapon can be chosen to be picked up by an NPC. Something like a SWEP:CanBePickedUpByNPCs() function in Lua, if at all possible, would be extremely helpful.

Something like a function to force an NPC to attempt to pick up a weapon would also be very useful, something like NPC:PickUpWeapon(weapon).

**Comment by robotboy655** [comment] 2019-08-05 16:28
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/933

**Closed by robotboy655** 2019-08-05 16:28 UTC

**Comment by robotboy655** [comment] 2019-08-06 13:05
FYI CanBePickedUpByNPCs returns true for all weapons by default, so its not even the problem.
