### ISSUE TITLE
Add engine.TickRate

### ISSUE THREAD

**Issue by Kinyom** [Facepunch/garrysmod-requests#1802] opened 2021-02-17 01:12 UTC
### Details
Basically, just a function that directly returns the engine's tickrate, instead of needing to call `1 / engine.TickInterval()`.

### Why not just use `1 / engine.TickInterval`?
This is admittedly an _extremely_ niche and picky use, but in the case somebody wants to do accurate time calculations based off tickrate, the small imprecision introduced with C++ calculating the inverse first can be a bit of a nuisance.

E.g, if you wanted to check your server tickrate - and it was an exact number like 30, 60, 90, or 100 - re-dividing `engine.TickInterval()` would give you a slightly-off number:
- `30 - 29.999998435378`
- `60 - 59.999996870756`
- `90 - 89.999997820705`
- `100 - 100.00000223517`

### Okay - why not just round it?
A few reasons.
- Some newer coders not as well versed in float imprecision might not be aware of this issue, and end up doing `1/engine.TickInterval() == 100` checks and such, then have no idea what's going wrong.
- The value is already there in the engine - why not offer it to coders directly?
- Assuming an integer tickrate this pretty much just locks you off from getting a more precise value than even what's in the engine, which as I mentioned before can make doing precise calculations a hassle.

This request is admittedly pretty trivial, so I don't expect it to be a top priority, but I do hope it's implemented at some time.

**Comment by thegrb93** [comment] 2021-02-17 06:08
Server tick rate values can be 33.3333... 66.66666... and 100hz. the floating imprecision is too minuscule to matter.

**Comment by Kinyom** [comment] 2021-02-17 06:38
> Server tick rate values are 33.3333... 66.66666... and 100hz. the floating imprecision is too minuscule to matter.

I'm pretty sure server tickrates can be anything from 10 to 100hz, at least if the SDK is anything to go by. I have mine set to 60.

**Comment by robotboy655** [comment] 2021-02-17 14:39
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1489

**Closed by robotboy655** 2021-02-17 14:39 UTC
