### ISSUE TITLE
Add Closed Captions Dynamically

### ISSUE THREAD

**Issue by Denneisk** [Facepunch/garrysmod-requests#2084] opened 2023-05-04 20:03 UTC
Closed captions are a very useful feature especially for those hard of hearing, and it would be great if addon developers could have access to adding CC easily.

This is slightly different from other suggestions but achieves the same effect:

Similar to how `sound.Add()` adds a sound to the soundscript, why not have something to dynamically add a closed caption/subtitle to the caption table?

An alternative could be to provide precompiled .dat files and having the engine handle them on game start.

**Comment by robotboy655** [comment] 2023-05-04 20:13
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/2024

**Closed by robotboy655** 2023-05-04 20:13 UTC
