### ISSUE TITLE
Add Proper Hit Animations for Zombies

### ISSUE THREAD

**Issue by checkthebioman** [Facepunch/garrysmod-requests#2436] opened 2024-07-25 19:45 UTC
So there's a feature in Episodes where if you shoot a Zombie in a specific part he will flinch. For example: If you shoot him in the leg he will fall to check his leg and stand up, etc. I think you got my point.

**Comment by robotboy655** [comment] 2024-07-25 23:51
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5945

**Closed by robotboy655** 2024-07-25 23:51 UTC
Labels: Content
