### ISSUE TITLE
engine.ServerFrameTime() serverside

### ISSUE THREAD

**Issue by bewflast** [Facepunch/garrysmod-requests#1996] opened 2022-07-16 11:30 UTC
How do you do!

There is very useful function on client-side named "engine.ServerFrameTime()" which shows up server's current tickrate

It would be very useful to have it on server-side too 🥺 (e.g detecting server's low performance and do some manipulations to stabilize it)
I know, that there are few ways do detect it through time's functions or binary module, but getting current tickrate on server-side is a more accurate and simple method 😄

**Comment by awesomeusername69420** [comment] 2022-07-16 11:57
Use FrameTime()

**Comment by Kefta** [comment] 2022-07-16 15:49
FrameTime on the server is gpGlobals->frametime while RealFrameTime is gpGlobals->absoluteframetime. Like I said in your last issue, duplicate of https://github.com/Facepunch/garrysmod-requests/issues/482.

**Comment by bewflast** [comment] 2022-07-16 16:19
> Use FrameTime()

bruh
https://youtu.be/GesvdOnuzj8

**Comment by awesomeusername69420** [comment] 2022-07-16 18:26
The client number is an estimation, not the actual server amount, the client side is susceptible to ping and packet loss interference

**Comment by bewflast** [comment] 2022-07-16 21:58
im talking about static value of FrameTime() serverside not engine.ServerFrameTime()'s impossible values

**Closed** 2022-08-01 14:18 UTC
Labels: Duplicate
