### ISSUE TITLE
Make PhysObj.SetMaterial affect surfaceprops for players again

### ISSUE THREAD

**Issue by Jvs34** [Facepunch/garrysmod-requests#85] opened 2013-08-08 10:23 UTC
This used to work back in the beta, you just had to use Entity(1):GetEyeTrace().Entity:GetPhysicsObject(): SetMaterial("slipperymetal") and it would make it slippery, but it doesn't anymore.
It works on sents with  EnableCustomCollisions though.
(Updated the title)

**Comment by thegrb93** [comment] 2015-06-24 00:27
I was about to request physobj:SetMaterial affect footstep sounds and bullet impacts, but I found this request and it seems to be related enough. Hopefully footstep sounds and bullet impacts get added along with this.

**Comment by robotboy655** [comment] 2020-09-30 16:04
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1089

**Closed by robotboy655** 2020-09-30 16:04 UTC
