### ISSUE TITLE
GM:CanOpenMenu

### ISSUE THREAD

**Issue by Be1zebub** [Facepunch/garrysmod-requests#2072] opened 2023-03-31 14:10 UTC
A way to block game menu open. 
Why? At this time there is no way to complete block menu, [gui.HideGameUI()](https://wiki.facepunch.com/gmod/gui.HideGameUI) in PreRender makes menu blink in 1 frame. 
This would save players from epilepsy attacks while closing in-game menus using escape or opening custom escape menus. 
It's just a QOL change, which is not something important - but it would really make the game more pleasing to the eye.

**Comment by robotboy655** [comment] 2024-05-08 11:55
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1624

**Closed by robotboy655** 2024-05-08 11:55 UTC
