### ISSUE TITLE
SYS Info/HWID

### ISSUE THREAD

**Issue by pparadoxx** [Facepunch/garrysmod-requests#1632] opened 2020-06-20 21:09 UTC
I'm sure this has been requested a lot and denied a lot however I just wanted to ask if the GLua Team could add more info on the computer the game is being run on. Im trying to make a HWID ban (Bans based on computer info, and SteamID). Im aware its a method of privacy but doesn't have to be too deep, just something like there type of CPU or GPU things like that.

You could even scratch all of that and just have a HWID value that the server can call.

(And yes im aware this has been asked before but it was never denied even tho it's 4 years old so I thought I could just bring it up again)

**Comment by GitSparTV** [comment] 2020-06-20 21:44
Duplicate of #745

**Closed** 2020-06-21 01:03 UTC

**Comment by TuXEKRO** [comment] 2022-09-12 11:34
I agree that we should have an option to be able to locate users by their hardware (since the Steam API closed the ability to see if the game was shared by another banned person). It would also help create statistics and be able to optimize both addons and servers to the hardware of most users.
