### ISSUE TITLE
allow GetConVar("sv_password") on the server

### ISSUE THREAD

**Issue by mgetJane** [Facepunch/garrysmod-requests#2345] opened 2024-03-31 12:41 UTC
you can already get its value in a  less convenient way through the [GM:CheckPassword](https://wiki.facepunch.com/gmod/GM:CheckPassword) hook

i guess maybe also add a convar that disables GetConVar("sv_password") and the GM:CheckPassword hook if it's really a security concern

**Comment by mgetJane** [comment] 2024-03-31 12:52
my use case is basically just for checking if the server has a password or not

maybe a function called something like `game.IsPasswordProtected()` would be nice if getting sv_password's contents without GM:CheckPassword is infeasible for whatever reason

**Comment by garryspins** [comment] 2024-04-01 05:06
Yea this doesn't make a whole lot of sense

**Comment by robotboy655** [comment] 2024-04-01 06:02
No.

**Comment by robotboy655** [comment] 2024-04-01 06:02
Also duplicate of https://github.com/Facepunch/garrysmod-requests/issues/2067

**Closed by robotboy655** 2024-04-01 06:02 UTC
