### ISSUE TITLE
csgo features in the stock compilers (gmod)

### ISSUE THREAD

**Issue by Unusuario2** [Facepunch/garrysmod-requests#2264] opened 2024-01-14 21:49 UTC
### Details
vbsp:
implement Static_Prop_Combine into vbsp and also -blocksize which controls visleaf splitting
https://developer.valvesoftware.com/wiki/Static_Prop_Combine
vrad:
implement ambient occlusion and all improvements of the lighting of props (-aoscale, -StaticPropLightingFinal, -StaticPropBounce, ect..)

**Comment by robotboy655** [comment] 2024-01-15 14:36
Partial duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1460

**Comment by Freezgam03** [comment] 2024-01-19 22:10
For Static Prop Combine, you can use [TeamSpen's Hammer Addons](https://github.com/TeamSpen210/HammerAddons)

**Comment by robotboy655** [comment] 2024-04-04 10:34
* `-blocksize` was added (Duplicate of #2208)
* Ambient Occlusion was added (aoscale too)
* Static_Prop_Combine is duplicate of #1460 

For the rest you can open a new request.

**Closed by robotboy655** 2024-04-04 10:34 UTC
Labels: Tools

**Comment by Unusuario2** [comment] 2024-05-09 14:45
thanks!
