### ISSUE TITLE
Add OnScreenResolutionChanged Hook

### ISSUE THREAD

**Issue by Luabee** [Facepunch/garrysmod-requests#881] opened 2016-12-21 08:52 UTC
A hook which gets called as the screen resolution changes would be useful for adjusting VGUI and HUD positions and sizes. Right now the alternative is repositioning and resizing in a think hook.

The hook could be something like this:
`GM:OnScreenResolutionChanged(oldw, oldh, neww, newh)`

It would be clientside only.

**Comment by neico** [comment] 2016-12-21 08:58
Technically a good request, but I think [PerformLayout](http://wiki.garrysmod.com/page/PANEL/PerformLayout) is better suited for that (which should be called on all screen size changes, if it doesn't that's maybe something to request instead) as it essentially does what you describe

**Comment by Jvs34** [comment] 2016-12-21 10:07
Duplicate of #432

**Closed** 2016-12-21 10:22 UTC
