### ISSUE TITLE
env_sprite_clientside for GMod Hammer

### ISSUE THREAD

**Issue by Fishke1** [Facepunch/garrysmod-requests#1493] opened 2020-01-19 09:23 UTC
env_sprites use up entdata unnecessarily as most of the time you use them as visual enhancers for static light sources, and aren't going to move/switch states at all

https://developer.valvesoftware.com/wiki/Env_sprite_clientside

**Comment by robotboy655** [comment] 2020-01-19 15:00
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1282

**Closed by robotboy655** 2020-01-19 15:00 UTC
