### ISSUE TITLE
Add EyeFOV()

### ISSUE THREAD

**Issue by marchc1** [Facepunch/garrysmod-requests#2323] opened 2024-03-16 23:18 UTC
### Details
Add a method similar to EyePos and EyeAngles in functionality but for FOV, where the return value can be modified by the CalcView hook

**Comment by Kefta** [comment] 2024-03-16 23:41
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1014.

**Closed as completed** 2024-03-17 00:15 UTC
