### ISSUE TITLE
Add server side hook for when a player requests a full update packet

### ISSUE THREAD

**Issue by LeQuackers** [Facepunch/garrysmod-requests#1762] opened 2020-12-01 19:58 UTC
Full update packets are requested/sent whenever the client needs to resync with the server. Adding a hook for this would help pretty much anything that needs to stay in sync over the network, notably replication that uses the net library.

https://github.com/VSES/SourceEngine2007/blob/master/src_main/engine/baseclient.cpp#L1185

**Comment by robotboy655** [comment] 2020-12-01 20:14
Potentially duplicate of https://github.com/Facepunch/garrysmod-requests/issues/204

**Comment by robotboy655** [comment] 2020-12-03 16:59
Added as `OnRequestFullUpdate` game event, we can't really have Lua in engine.dll
It has all the same data as `player_connect_client` event, save for `bot` field.

https://wiki.facepunch.com/gmod/gameevent.Listen

**Closed by robotboy655** 2020-12-03 16:59 UTC
