### ISSUE TITLE
Start pushing chromium to main

### ISSUE THREAD

**Issue by Thepenguin9** [Facepunch/garrysmod-requests#1225] opened 2018-10-17 15:23 UTC
I am aware that the chromium branch is available for those who wish to watch/listen to YouTube in-game, however I think now is a better time than any to start migrating from awesomium to chromium.

**Comment by Shaknunic** [comment] 2018-10-17 21:51
Hahahahaha! I don't  think they will since it's not even ready to release, also awesomium is using chromium too, but just an old version... The plan was to update to a new version, but looking in some post here, they're preparing for this update since 2015, yeah the process is long, but they will when they are ready to do so, for now it still has many issues to solve it...

**Comment by Thepenguin9** [comment] 2018-10-18 05:43
I know aawesomium is chromium based, however I'm asking that we have chromium itself be part of main

**Comment by chelog** [comment] 2018-10-23 10:31
I personally think if we push chromium to main now, we will have FAR LESS issues than we do have now with this goddamn Awesomium. Please, do hurry with chromium merge, it's must-have in gmod right now.

**Comment by robotboy655** [comment] 2018-10-23 13:08
Basically duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3119

**Closed by robotboy655** 2018-10-23 13:08 UTC
