### ISSUE TITLE
Allow selecting no weapon (empty hands)

### ISSUE THREAD

**Issue by Tripperful** [Facepunch/garrysmod-requests#1571] opened 2020-04-18 18:30 UTC
The only way to do this at the moment is to delete player's active weapon, if you pass NULL to any function that handles weapon selection, it throws an error.

Could be implemented by allowing to pass NULL to functions like Player.SetActiveWeapon,  CUserCmd.SelectWeapon, input.SelectWeapon or at least one of them.

Why should player always have an active weapon if it has any? Looks like an old limitation from HL:2 that should've been already removed in gmod, but for some reason it still isn't.

**Comment by Kefta** [comment] 2020-04-18 23:33
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/893.

**Comment by robotboy655** [comment] 2020-04-20 14:01
Duplicate of #893.

**Closed by robotboy655** 2020-04-20 14:01 UTC
