### ISSUE TITLE
GetListOfPenetratingEntities

### ISSUE THREAD

**Issue by Ramalayha** [Facepunch/garrysmod-requests#1640] opened 2020-06-25 10:40 UTC
Having access to [this function](https://github.com/whoozzem/SecobMod/blob/master/mp/src/game/server/physics.cpp#L822)  would be nice.

**Comment by mcNuggets1** [comment] 2020-07-10 03:36
Omega yes

**Comment by robotboy655** [comment] 2020-07-16 17:27
What for?

**Comment by Kefta** [comment] 2020-07-16 19:41
To check if players are stuck inside multiple players/ents as traces only return one HitEntity I'm guessing. But that function is kind of useless anyway because it's not accurate: https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/server/physics.cpp#L893 (the penetration event will stay in the list for one second once they stop penetrating)

Instead, having a ShouldSolvePenetration callback would be more useful.

Also @robotboy655, ``CCollisionEvent::ShouldSolvePenetration`` is one of the offenders that assumes the physobjs' gamedatas are a valid ``CBaseEntity``s. I looked thru the vphysics internals and not only does it not require the gamedata to be valid, it doesn't even know about ``CBaseEntity``. Can you fix this so we can have independent physobjs?

**Comment by Ramalayha** [comment] 2020-07-17 07:29
> What for?

The thing I'm trying to do in my script is spawning a collection of props and weld together those that are touching eachother, but another use I can think of is detecting prop spam.

**Comment by robotboy655** [comment] 2020-07-20 13:59
For the first case you could maybe use this: https://wiki.facepunch.com/gmod/ENTITY:PhysicsCollide

I don't see how this could help with prop spam, for SPAM you usually use timing, not interpenetrating entities, and the issue is that the function is per entity, it's not a global that returns all entities that are penetrating, which could've been used  to detect those "server crasher" dupes or something

**Comment by Ramalayha** [comment] 2020-07-21 08:45
Oh I didn't think about using PhysicsCollide, thanks :)

**Comment by robotboy655** [comment] 2020-07-21 12:31
Closing this then, since it's not all that useful as initially expected.

**Closed by robotboy655** 2020-07-21 12:31 UTC
