### ISSUE TITLE
Make Entity:GetCreationID shared

### ISSUE THREAD

**Issue by MattJeanes** [Facepunch/garrysmod-requests#538] opened 2015-07-14 05:24 UTC
`Entity:GetCreationID()` is currently serverside for some reason. It would be cool to have this clientside too for stuff that requires unique numbers that will never be re-used.

**Comment by robotboy655** [comment] 2015-10-12 13:21
Dupe of #218

**Comment by Kefta** [comment] 2019-12-09 02:37
This is not a dupe of #218 - that issue is asking for MapCreationID to be shared, this is asking for GetCreationID to be shared.

**Comment by GitSparTV** [comment] 2020-03-01 16:34
Bump, this is what I really wanted for making custom NW system using networking.
For example I had SetNWTable that attaches a table to the entity (like SetNWInt but for tables, don't confuse with NWVarTable). The data is sent instantly and sometimes it can be received faster than the entity is created on client. This can cause collisions in situations when you create an entity, send some information about it, then remove the entity and create the new one. Server can use the same EntIndex and the data will be stored on wrong entity on client.

**Comment by GitSparTV** [comment] 2020-08-10 23:05
Bump, at least add labels

**Comment by Kefta** [comment] 2020-08-10 23:51
It's high on my todo list.

**Comment by thegrb93** [comment] 2021-04-08 07:04
This will be useful someday.

**Comment by robotboy655** [comment] 2023-06-26 20:36
Done. It is now shared.

**Closed by robotboy655** 2023-06-26 20:36 UTC
Labels: Request, Complexity: Low, Net-Compat-Breaking

**Comment by MattJeanes** [comment] 2023-06-27 00:32
Awesome, thank you! Is this live now or in an upcoming patch?

**Comment by MattJeanes** [comment] 2023-06-30 03:45
I can see this has now gone live 🙂 - after all these years finally I can use it, cheers!
