### ISSUE TITLE
The ability to search ConVars from Lua

### ISSUE THREAD

**Issue by LoganDark** [Facepunch/garrysmod-requests#1222] opened 2018-10-15 23:15 UTC
I want some Lua function that works like `cvarlist`. For example, `SearchConVars('sbox_max')` would return a table of all the ConVars that control max amounts of things (like `sbox_maxthrusters`, `sbox_maxlights`, etc.)

This could be immensely useful, because right now there's no way to get ConVars via Lua, and also no way to run commands via Lua (and get the output), so running `cvarlist` is a no-go.

**Comment by robotboy655** [comment] 2023-11-03 15:18
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/341

**Closed by robotboy655** 2023-11-03 15:18 UTC
