### ISSUE TITLE
Hooks for the voice

### ISSUE THREAD

**Issue by MoskalykA** [Facepunch/garrysmod-requests#2095] opened 2023-05-31 22:04 UTC
### Details
I suggest adding a server-side version of these two hooks:
- https://wiki.facepunch.com/gmod/GM:PlayerEndVoice
- https://wiki.facepunch.com/gmod/GM:PlayerEndVoice

**Comment by FlorianLeChat** [comment] 2023-06-01 07:20
Duplicate of #163

**Closed** 2023-06-01 11:43 UTC
Labels: Duplicate
