### ISSUE TITLE
Don't print "lua/includes/module.lua (File not found)" error on failed require

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#813] opened 2016-08-31 19:32 UTC
require already throws an error when it fails to find a file -- printing this is redundant and makes it unpreventable if you use require w/ pcall.

**Comment by meepdarknessmeep** [comment] 2016-09-04 22:34
Maybe it should be print
`Couldn't find library '%s'`

**Comment by robotboy655** [comment] 2023-11-10 13:56
`require` calls `include` for Lua modules, and thus has same issues as it in relation to `pcall`.

Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2498

**Closed by robotboy655** 2023-11-10 13:56 UTC
