### ISSUE TITLE
Please implement the Lightmapped_4WayBlend shader

### ISSUE THREAD

**Issue by Ammarillo** [Facepunch/garrysmod-requests#2056] opened 2023-02-06 11:33 UTC
I'm currently working on a new map and would love to use the `Lightmapped_4WayBlend` shader.

**Comment by robotboy655** [comment] 2023-02-06 15:08
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1437

**Closed by robotboy655** 2023-02-06 15:08 UTC
Labels: Shaders
