### ISSUE TITLE
Add a Lua binding to get the model precache number

### ISSUE THREAD

**Issue by wrefgtzweve** [Facepunch/garrysmod-requests#2375] opened 2024-04-30 15:30 UTC
### Details
Currently there is simply no way to reliably get the model precache, which is rather annoying as it instant crashes the server when it gets hit.
There is a way to see it right now, just not through lua. Running `dumpstringtables_new` shows the count.
```lua
1: modelprecache
strings: 1442
strdata: 50887
databts: 1442
```

Having some kind of function like `engine.GetModelPrecacheCount() number` would be incredibly useful and should be relatively simple to implement.

**Comment by robotboy655** [comment] 2024-04-30 15:38
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/82

Thanks for using the search feature.

**Closed by robotboy655** 2024-04-30 15:38 UTC
