### ISSUE TITLE
PostEntityFireBullets hook or alternative for breaking returns

### ISSUE THREAD

**Issue by wrefgtzweve** [Facepunch/garrysmod-requests#2207] opened 2023-11-13 15:23 UTC
### Details
Currently `EntityFireBullets` allows you to return true or false to apply changes, which inherently breaks the hook chain which means that multiple addons using this hook would conflict and break eachother.
![image](https://github.com/Facepunch/garrysmod-requests/assets/69946827/39008994-2788-4e3e-9861-cb6961ab4128)

So my request is some kind of PostEntityFireBullets that can be reliably used without the possibility of conflicts.
Another good feature would be https://github.com/Facepunch/garrysmod-requests/issues/1845 which would partially resolve this issue too as it'll reduce the amount of people needing to modify the callback and thus having to return true in `EntityFireBullets`.

**Comment by robotboy655** [comment] 2023-11-13 15:29
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1845

**Closed by robotboy655** 2023-11-13 15:29 UTC
