### ISSUE TITLE
Ideas about maps (Increase map size and other)

### ISSUE THREAD

**Issue by alman74** [Facepunch/garrysmod-requests#1599] opened 2020-05-21 13:43 UTC
1. Do you plan to increase the maximum map size? And remove the maximum map size limit? 
Although increase the size by 1.5-2 times more...

2. Can you add circular maps and rectangular maps?

3. If the answers are negative, I want to ask why you can't do this?

(I hope you understand, if not, then forgive my English)

**Comment by robotboy655** [comment] 2020-05-21 13:50
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/448

**Closed by robotboy655** 2020-05-21 13:50 UTC

**Comment by VaasKahnGrim** [comment] 2020-05-21 14:05
with max map size iirc the issue was that they would have to change a specific thing for vectors to be able to actually store info for it along with something else(I think regarding PVS and PAS, been a while)

As for circular maps, it depends on how you setup your brush work(alternatively using models would be better for circular things in source) if you mean circular as in how a planet is round, like say in other games such as space engineer or something, you'd be able to do that already by simply having that handled via lua.

and as for rectangular maps, thats always been a thing lmao

**Comment by alman74** [comment] 2020-05-21 17:11
I appreciate your answers. My second question was unclear due to an error in my English. 
I don't think I have any questions. Thanks!
