### ISSUE TITLE
Add ISteamHTMLSurface to Gmod

### ISSUE THREAD

**Issue by DarthTealc** [Facepunch/garrysmod-requests#2494] opened 2024-10-16 09:03 UTC
### Suggestion
Add ISteamHTMLSurface to Gmod

### Details / Why
Awesomium (main branch) is based on Chrome 18 which is incredibly outdated and is running on early 2012 web standards. It does not support modern TLS. It doesn't support calc() which is supported in Internet Explorer 9. 
CEF (x86-64 branch) is based on Chrome 86 which is from 2020. [WinterPhoenix has a pull to update it to 124](https://github.com/Facepunch/gmod-html/pull/3) but the request has been ignored and unlikely to happen.

A solution to this could be adding [ISteamHTMLSurface](https://partner.steamgames.com/doc/features/html_surface). It would automatically be kept up to date as Valve updates the Steam Client and would not require further work from Facepunch.

### To Resolve
- [ ] Requirement: ISteamHTMLSurface needs a way to isolate the session/cookie storage from the main Steam client/overlay session.

ISteamHTMLSurface uses the same session as the Steam client/overlay, which would be a major issue with random mods and servers having LUA access to the panel. Valve would need to add a way for games to use ISteamHTMLSurface with an isolated session/cookie storage. It should NOT be implemented until this is resolved. As Facepunch has contacts at Valve, the first step could be to reach out and see if they're able to fix this.

**Comment by robotboy655** [comment] 2024-10-16 12:11
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/791

**Closed by robotboy655** 2024-10-16 12:11 UTC
