### ISSUE TITLE
HitBox OBB check disabling

### ISSUE THREAD

**Issue by Goldermor** [Facepunch/garrysmod-requests#2007] opened 2022-08-07 19:48 UTC
Can you add the ability to disable OBB checking for hitboxes? I'm don't know how exactly it works. is it possible to do this for a specific entity?
Like Entity:HitBoxOBBCheck( true/false ). To be able to hit hitboxes that are outside the obb. 
if such a possibility already exists - I'm sorry, I couldn't find it.

**Comment by robotboy655** [comment] 2022-08-08 01:22
Why would you want to disable it?

**Comment by Goldermor** [comment] 2022-08-09 12:01
> Why would you want to disable it?

Some models may have shapes and animations that will not match with OBB. making OBB bigger restricts movement.
most of all, this applies to long creatures and big models.
![obbtest](https://user-images.githubusercontent.com/77431249/183642004-14b415b6-c88a-43c0-a44e-f39897b86d7e.png)
![obbtest1](https://user-images.githubusercontent.com/77431249/183642015-fdba7d5a-4ea7-44f0-8b5f-abd52378b24e.png)

**Comment by Goldermor** [comment] 2022-08-09 12:02
this is the same thing that happens to soldier in TF2, and it was fixed by Valve

**Comment by Goldermor** [comment] 2022-08-09 17:25
> You can already hit hitboxes outside of OBB.
but how, lol
it just doesn't work

**Comment by Goldermor** [comment] 2022-08-09 17:26
> You can already hit hitboxes outside of OBB.

but how, lol
it just doesn't work

**Comment by robotboy655** [comment] 2022-08-09 17:32
Related issue/duplicate of:
https://github.com/Facepunch/garrysmod-requests/issues/1929

I have tested with antlion guard and it works fine for it, but not for fast zombies. Perhaps adding function requested in the issue above will solve the problem.

**Comment by Goldermor** [comment] 2022-08-09 18:30
as I see, NPCs like guardian use a thing called absbox
perhaps this thing is sets automatically with OBB
maybe you should add functions like Entity:SetABSBox( Vector mins, Vector maxs ) if so
![obbtest2](https://user-images.githubusercontent.com/77431249/183733575-d1e1c990-7b53-4db3-9a18-44bc6680913f.png)

**Comment by robotboy655** [comment] 2022-08-12 14:54
Added `Entity:SetSurroundingBounds( mins, maxs )` and `Entity:SetSurroundingBoundsType( BOUNDS_  )`

They are mutually exclusive, `BOUNDS_ ` values can be `BOUNDS_HITBOXES` which will make the game try to set the bounds to fit all hitboxes, and `BOUNDS_COLLISION` to use the Entity's collision bounds, which is also the default value for most entities.

The mins and maxs are of an AABB, not OBB!

Also added `mins, maxs = Entity:GetSurroundingBounds()` which will get you the Calculated AABB of the surrounding bounds.

**Closed by robotboy655** 2022-08-12 14:54 UTC
Labels: Duplicate
