### ISSUE TITLE
Dynamic RTT Shadow Angles

### ISSUE THREAD

**Issue by Kemerd** [Facepunch/garrysmod-requests#524] opened 2015-07-03 00:09 UTC
https://developer.valvesoftware.com/wiki/Dynamic_RTT_shadow_angles_in_Source_2007

Do you think it would be possible to implement something like this into Garrysmod? (Even though it is 2007 code.)

Thanks.

> obsessed with shadows and lighting

**Comment by FirstRoboticsGuy999** [comment] 2015-07-15 14:01
The code is probably obsolete. There' s no point taking the time to rewrite the code and implement it if the shadows already work fine enough.

**Comment by robotboy655** [comment] 2019-09-24 16:47
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1302
( I know this issue is older )

**Closed by robotboy655** 2019-09-24 16:47 UTC
