### ISSUE TITLE
Implement particle rain/snow from Alien Swarm?

### ISSUE THREAD

**Issue by Havch1k92** [Facepunch/garrysmod-requests#976] opened 2017-06-01 15:39 UTC
https://github.com/Sandern/aswscratch/blob/master/src/game/client/c_effects.cpp

**Comment by Kefta** [comment] 2017-06-01 17:01
Similar to https://github.com/Facepunch/garrysmod-requests/issues/779

**Comment by robotboy655** [comment] 2017-06-01 17:19
Not at all, duplicate of #809 really.

**Closed by robotboy655** 2017-06-01 17:19 UTC

**Comment by Kefta** [comment] 2017-06-01 23:55
Oh I didn't see his link, I thought it was an effect not an actual entity
