### ISSUE TITLE
Add NPC:GetCurrentScene

### ISSUE THREAD

**Issue by URAKOLOUY5** [Facepunch/garrysmod-requests#2513] opened 2024-10-29 20:06 UTC
### Details
There's no way to find out SceneEntity on NPC (to check if it speaking, for example)

In C++ for GetCurrentScene (on BaseFlex):

```cpp
CSceneEventInfo curScene = m_SceneEvents.Head();

return (CBaseEntity*)(curScene.m_hSceneEntity.Get());
```

**Comment by robotboy655** [comment] 2024-10-29 20:20
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/2274

**Closed by robotboy655** 2024-10-29 20:20 UTC
