### ISSUE TITLE
Add support for the light_directional entity

### ISSUE THREAD

**Issue by Mingooberus** [Facepunch/garrysmod-requests#2132] opened 2023-07-15 19:26 UTC
### Details
Stated here https://developer.valvesoftware.com/wiki/Light_directional "light_directional is a point entity available in all Source games since  Left 4 Dead. It is a directional light with no falloff, similar to the direct lighting of Light Environment."

Simply add this for the benefits it would bring to mapping and coordinating lighting for maps.

**Comment by robotboy655** [comment] 2023-07-17 13:33
Related/Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1577

**Closed** 2023-07-17 14:57 UTC
