### ISSUE TITLE
SourceTV support

### ISSUE THREAD

**Issue by CaptainPRICE** [Facepunch/garrysmod-requests#1271] opened 2019-01-20 01:11 UTC
[Wiki](https://developer.valvesoftware.com/wiki/SourceTV).
> Not working in Gmod 13. The game crashes on `tv_record` including dedicated servers.

**Make it work** - seriously!
I'm trying to accomplish complex task as a part of the gamemode, but it is impossible when your tools crash.
😞

[Store](https://store.steampowered.com/app/4000):
> We give you the tools and leave you to play.

**Comment by robotboy655** [comment] 2019-01-21 09:42
Possibly duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1934

**Closed** 2023-11-03 15:07 UTC
