### ISSUE TITLE
Expose Entity.RemoveInternalConstraint to clientside Lua

### ISSUE THREAD

**Issue by ZakBlystone** [Facepunch/garrysmod-requests#2560] opened 2024-12-14 03:19 UTC
### Details
I am currently doing this in a binary module but I cannot easily distribute it with an addon I am working on.
My C++ implementation is similar to #1217 but targeting `m_pRagdoll->m_ragdoll` on `C_BaseAnimating` as opposed to `m_ragdoll` on `CRagdollProp`

Also if possible, an additional function to find the index of an internal constraint via 2 physics objects (also available on server / client).
Something akin to:
```cpp
for (int i = 0; i < m_ragdoll.listCount; ++i) {
	const ragdollelement_t &element = m_ragdoll.list[i];
	if (element.pConstraint == nullptr) continue;
	if (element.pConstraint->GetReferenceObject() == obj_a && element.pConstraint->GetAttachedObject() == obj_b) {
		return i;
	}
	if (element.pConstraint->GetReferenceObject() == obj_b && element.pConstraint->GetAttachedObject() == obj_a) {
		return i;
	}
}
```
where `obj_a` and `obj_b` are two `IPhysicsObject` passed in via Lua.

Thank you for your time.

**Comment by robotboy655** [comment] 2024-12-14 10:16
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/2328

**Closed by robotboy655** 2024-12-14 10:16 UTC
