### ISSUE TITLE
The "Are you sure to connect to this server?" Dialog needs to be reworked.

### ISSUE THREAD

**Issue by catSIXe** [Facepunch/garrysmod-requests#1854] opened 2021-04-21 03:47 UTC
### Details
`LocalPlayer():ConCommand("connect ".. ip)`

This Dialog is really annoying, as it ALWAYS asks you to join. It should be possible to Remember the Choice/Whitelist a Domain (because IPs could change).

![image](https://user-images.githubusercontent.com/63829136/115493773-a98dbd80-a264-11eb-8047-c39085bd31ae.png)

We use Travelling Transitions between servers, it breaks continuity, since we are prompting the user if they want to leave anyway, it's redundant and un-neccesary.

Games like Multi-Theft-Auto : San Andreas already implemented such Features, without being annoying.

https://wiki.multitheftauto.com/wiki/RedirectPlayer

**Comment by robotboy655** [comment] 2021-04-21 09:04
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1751

**Closed by robotboy655** 2021-04-21 09:04 UTC
