### ISSUE TITLE
Allow us to file.Write .MDL into data folder

### ISSUE THREAD

**Issue by KingDavidW** [Facepunch/garrysmod-requests#1883] opened 2021-06-30 18:27 UTC
### Details
This is a straight forward request to add the .MDL extension to file.Write's whitelist. The restriction seems arbitrary considering it would always be contained in the data folder and must be directly referenced, so you would never be able to overwrite someone's existing models.

Of my research, models are not restricted by the models path, but they are restricted by the extension in the SetModel function. You could technically write an entire model into a file of different extension, and it would work if the function allows it. I can immediately test this by setting my model to "data/test.mdl" and it working perfectly fine, but "data/test.dat" failing. That's because internally models can load any file type so long as their headers are intact.

This opens up the door to dynamic model management especially when some are being cached. It also seems completely trivial to add

**Comment by Kefta** [comment] 2021-07-01 02:46
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1552

**Closed** 2021-07-05 13:15 UTC
