### ISSUE TITLE
Re?Implementation of Particle System's render_model and render_blobs Renderers

### ISSUE THREAD

**Issue by DeffOS** [Facepunch/garrysmod-requests#1685] opened 2020-08-15 21:13 UTC
https://developer.valvesoftware.com/wiki/Particle_System_Renderers#render_blobs
They are default for SDK 2009 so in theory already exists in code it self.

**Comment by robotboy655** [comment] 2020-08-17 15:13
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1279

**Closed by robotboy655** 2020-08-17 15:13 UTC
