### ISSUE TITLE
Lua way to toggle r_shadowfromanyworldlight  for servers

### ISSUE THREAD

**Issue by Akabenko** [Facepunch/garrysmod-requests#2401] opened 2024-06-04 22:07 UTC
I’ve seen reports that the dynamic light system doesn’t work without r_shadowfromanyworldlight enabled, so I support the idea of adding a way to toggle it serverside.

https://github.com/Facepunch/garrysmod-requests/issues/1458

**Comment by robotboy655** [comment] 2024-06-05 18:55
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1458

**Closed by robotboy655** 2024-06-05 18:55 UTC

**Comment by robotboy655** [comment] 2024-06-27 16:38
I have looked into this, and there was a bug with `vrad.exe` that made the option "Cast entity shadows" to not work in-game. This bug is fixed on `x86-64` beta, so if you (re)compile your map on that beta, the feature will work as expected on all versions of the game. 

Other versions of the game will also get the map compiler fix, but later.

I have also added extra info to that keyvalue on `light` entity about how to make it work properly.
