### ISSUE TITLE
Bind NPC functions to Lua

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-requests#1791] opened 2021-02-02 00:36 UTC
List of functions or enumeration requests to be binded to Lua. **THIS LIST IS CONSTANTLY UPDATED**
_All links point to 2013 source sdk on GitHub._

### EXPERIMENTAL
- None at the moment

### NOT ADDING / UNECESSARY
- [ ] `DeltaIdealYaw()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_motor.cpp#L780) ): This is a technical function, but this would help significantly with setting up a turning animation system for SNPCs. It would be much better to have it done in the engine itself then through Lua (In terms of performance and reliability). An example use of this would be to replicate [This](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_basenpc_schedule.cpp#L4164) function in Lua, which is something many people have wanted for their SNPCs.
- [ ] `GetCurSpeed()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_motor.h#L82) ): This is not very necessary to add as one could use the `GetCurVel()` and gets its length, but if you are welcome to add it, if you want to stay consistent to the engine.

### ADDED

> - [x] `SetActivity(activity)`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_basenpc.h#L930) ): Similar to `SetIdealActivity` but it ignores transition activities, useful to instantly snap the NPC to the given animation.
> - [x] `ResetIdealActivity(activity)`( [Link 1](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_basenpc.h#L933) [Link 2](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_basenpc_schedule.cpp#L4240) ): Also Similar to `SetIdealActivity` but this one resets the animation if needed. This is useful when playing idle animations or when the same exact animation is ran after it. Currently, only solution is to start a task with `TASK_RESET_ACTIVITY` which properly lets the animation repeat again, but this time it breaks walk frames. Hopefully with this function, this will be solved.
> - [x] `IsGoalActive()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_navigator.h#L371) ): Returns true if the current goal is actually active, it's different than `IsMoving` and shouldn't be confused with that.
> - [x] `ClearBlockingEntity()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/ai_basenpc.h#L1505) ): A simple function that resets the private variable m_hLastBlockingEnt, useful because in Lua we are able to call `GetBlockingEntity()` but no way to reset it when we clear the path, would have to wait until the engine realizes it.
> - [x] `GetNavType()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_navigator.h#L394) ): Currently the only way to know if an NPC is using a node to jump or climb is by getting the commonly used activities and hope that it's not being called by another system. Using this function, we can properly get the current Navigation type it's using. This will likely require binding the enumerations found [Here](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_navtype.h#L18).
> - [x] `SetNavType(NAV_ type)`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_navigator.h#L395) ): Opposite of above, not sure if this would work how I am thinking, but would be interesting to test.
> - [x] `GetMoveInterval()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_motor.h#L54) ): Allows to retrieve the current interval, note that this is useful for certain move types and it is different from the other movement accessors.
> - [x] `SetMoveInterval(interval)`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_motor.h#L55) ): Opposite of above (mutator), allows us to set change the variable.
> - [x] `MoveClimbStop()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_motor.h#L64) ): Many times, climb nodes can make an NPC stuck, in fact this is an issue for 75% of the time. With this function, I believe we can force stop the climbing through Lua. We could possibly use the other functions and know that the NPC is stuck and call this function to fix it.
> - [x] `MoveJumpStop()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_motor.h#L71) ): Basically same as above but for jumping. Although jumping is not as bugged as climbing, it has a chance of about 5-10% of the NPC getting stuck forever.
> - [x] `MoveStop()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_motor.h#L75) ): This is NOT like `StopMoving()` function, this actually stops the NPC! Since in Lua we don't have a proper way of stopping the NPC without calling a whole task or clearing goals, this would finally provide a way to do that! It would also finally solve the blending issue that occurs when attempting to stop an NPC quickly, often times its speed will bug out and it will teleport forward and backwards couple of times until the engine realizes it and fixes it (Usually lasts 2-4 seconds). I believe this function would stop that issue as it actually stops the movement, not just its velocity or animation.
> - [x] `GetCurVel()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_motor.h#L83) ): This is NOT the entity's velocity! This is the movement velocity, if we are finally able to get the NPC's movement velocity, this would be used in many places and fix many issues in SNPCs. If added, you are welcome to rename to something better if the naming is an issue.
> - [x] `MinStoppingDist(dist)`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_motor.h#L141) ): Unlike `SetArrivalDistance()`, this actually sets the distance needed until it begins stopping.
> - [x] `MinCheckDist()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_motor.h#L142) ): Returns the distance left until it reaches the stopping distance, it calculates using the function suggested above and couple other functions.
> - [x] `IsYawLocked()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_motor.h#L153) ): Useful function for turning system, allows us to retrieve whether or not the yaw is locked. This is used in many essential schedules and would be useful for Lua-defined tasks.
> - [x] `SetYawLocked(bool)`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_motor.h#L154) ): Set the variable for the function above to the given bool value, useful to make sure the engine does not override the yaw in cases where it should not.
>  - [x] `GetTaskStatus()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_basenpc.h#L755) ): This is an essential task function that returns the current task status. This will require binding the couple of enumerations found [Here](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_task.h#L69).
>  - [x] `SetTaskStatus(TaskStatus_e status)`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_basenpc.h#L754) ): The mutator of the above function, the argument should be the new enumerations described above. Useful if the task system is forced to change from Lua.
> - [x] `GetIdealSpeed()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_motor.h#L80) ): Widely used function for different NPCs, it's used for move speeds, this should be similar to IsJumpLegal function where it has a default functionality but we should also be able to override it so we can actually change it.
> - [x] `GetIdealAccel()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_motor.h#L81) ): Similar to above but it's more useful for initial movement. This should also have a default functionality with the ability to override it.
> - [x] `SetTurnActivity()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/ai_basenpc.h#L1732) ): Essential function to go along with some of the other functions, especially the ideal system and turning. Basically applies the turn animations depending on the current turn yaw. This is used in many NPCs in HL2.
> - [x] `HaveObstacles()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_localnavigator.h#L46) ): Returns true if the current navigation has a obstacle, this is different from blocking entity, this includes obstacles that it can steer around
> - [x] `AutoMovement()`( [Link 1](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_basenpc.h#L1505) [Link 2](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_basenpc_movement.cpp#L399) ): Basically as the function states "Execute any movement this sequence may have", this is useful because in Lua we are able to set the sequence or activity of an NPC, but their walk frames don't run unless a task schedule is ran with TASK_PLAY_SEQUENCE or TASK_PLAY_PRIVATE_SEQUENCE. This is not a very good solution as it won't work with actual sequences, only activities (ACT_*) and even then it's an awkward solution. Looking at these tasks, one can see the function AutoMovement being ran [Here](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_basenpc_schedule.cpp#L3311).
> - [x] `SetMoveVel(velocity)`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_motor.h#L191) ): This one is a little experimental, I think it may be able to change the velocity of the current movement? Basically the opposite of `NPC:GetMoveVelocity()`

Apologizes if these are a lot of functions. My goal is to give as much access as possible in Lua to the ai system in the engine. Since this is the third thread I have created related to this, if that's an issue, I would be happy to dedicate a single thread and add/update things as needed. Let me know if there is any questions, as always good luck and thank you!

**Comment by Kefta** [comment] 2021-02-02 01:38
Partial duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1182.

**Comment by Kefta** [comment] 2021-02-20 16:55
Added:
- void NPC:SetActivity( ACT_* )
- void NPC:ResetIdealActivity( ACT_* )
- bool NPC:IsGoalActive()
- void NPC:ClearBlockingEntity()
- NAV_* NPC:GetNavType()
- void NPC:SetNavType( NAV_* )
- NAV_NONE, NAV_GROUND, NAV_JUMP, NAV_FLY, NAV_CLIMB

AutoMovement will be added later today or early tomorrow, it requires some more testing. I did not add DeltaIdealYaw since it can be implemented as a stateless utility using the ideal yaw. Let me know if you want any of the accessors/modifiers of ai_motor bound and their potential use cases.

**Comment by DrVrej** [comment] 2021-02-20 20:11
> Added:
> 
> * void NPC:SetActivity( ACT_* )
> * void NPC:ResetIdealActivity( ACT_* )
> * bool NPC:IsGoalActive()
> * void NPC:ClearBlockingEntity()
> * NAV_* NPC:GetNavType()
> * void NPC:SetNavType( NAV_* )
> * NAV_NONE, NAV_GROUND, NAV_JUMP, NAV_FLY, NAV_CLIMB
> 
> AutoMovement will be added later today or early tomorrow, it requires some more testing. I did not add DeltaIdealYaw since it can be implemented as a stateless utility using the ideal yaw. Let me know if you want any of the accessors/modifiers of ai_motor bound and their potential use cases.

Thank you very much! I will test the functions and report back if I find any major issues. For the `DeltaIdealYaw`, I suggested it because from previous tests I found that calling a function from the engine is faster (performance) than calling a Lua function that replicates the same behavior, but it's not very important so no worries!

**NOTE:** I updated the thread with new functions to bind, I would be happy to maintain this single thread and update the description when something changes, I will post a notice comment if I add any new suggestions. Let me know if this is good or you would like me to create a new thread instead in the future. Thanks again and let me know if there are any questions!

**Comment by Kefta** [comment] 2021-02-20 20:21
The speed gain of DeltaIdealYaw's implementation is not significant enough to warrant a separate binding - I would rather bind primitive accessors/modifiers and intensive methods to maintain flexibility. I will check out binding the other functions you listed though.

**Comment by DrVrej** [comment] 2021-02-20 20:27
> The speed gain of DeltaIdealYaw's implementation is not significant enough to warrant a separate binding - I would rather bind primitive accessors/modifiers and intensive methods to maintain flexibility. I will check out binding the other functions you listed though.

No problem, let me know if you have any questions for the new suggestions. 👍

**Comment by Kefta** [comment] 2021-02-22 02:45
Added:
- `int [TASKSTATUS_*] NPC:GetTaskStatus()`
- `void NPC:SetTaskStatus(int [TASKSTATUS_*] status)`
- `TASKSTATUS_NEW`, `TASKSTATUS_RUN_MOVE_AND_TASK`, `TASKSTATUS_RUN_MOVE`, `TASKSTATUS_RUN_TASK`, `TASKSTATUS_COMPLETE`
<br>

- `float NPC:GetMoveInterval()`
- `void NPC:SetMoveInterval(float)`
- `float NPC:GetIdealMoveSpeed()`
- `float NPC:GetIdealMoveAcceleration()`
- `Vector NPC:GetMoveVelocity()`
- `float NPC:GetMinMoveStopDist()`
- `float NPC:GetMinMoveCheckDist()`
- `bool NPC:IsMoveYawLocked()`
- `void NPC:SetMoveYawLocked(bool bLocked)`
<br>

- `void NPC:MoveStart()`
- `void NPC:MoveStop()`
- `void NPC:MovePause()`
- `void NPC:ResetMoveCalc()`
<br>

- `void NPC:MoveClimbStart(Vector dest, Vector dir, float dist, float yaw)`
- `int [AIMR_*] NPC:MoveClimbExec(Vector dest, Vector dir, float dist, float yaw, int nodesLeft)`
- `void NPC:MoveClimbStop()`
- `AIMR_BLOCKED_ENTITY`, `AIMR_BLOCKED_WORLD`, `AIMR_BLOCKED_NPC`, `AIMR_ILLEGAL`, `AIMR_OK`, `AIMR_CHANGE_TYPE`
<br>

- `void NPC:MoveJumpStart(Vector vel)`
- `int [AIMR_*] NPC:MoveJumpExec()`
- `int [AIMR_*] NPC:MoveJumpStop()`

I did not add `NPC:GetCurSpeed()`/`NPC:GetMoveSpeed()` since you can derive it from `NPC:GetMoveVelocity():Length()`, which will give the exact result as the engine as both are floats.

**Comment by DrVrej** [comment] 2021-02-22 04:10
> Added:
> 
> 

This is awesome, thank you very much! I have also tested the functions you added yesterday and everything is working perfectly! I updated the thread to correspond to these changes. I am hoping in the future we could have basic access to the nodegraph of the map such positions, their hints/flags, etc. When I get the time I will put together a list and post it here (May take a while), thanks again!

**Comment by Kefta** [comment] 2021-02-24 00:39
Added:
- `float Entity:GetAnimTimeInterval() [CBaseAnimating]`
<br>

- `void NPC:SetTurnActivity()`
- `bool NPC:HasObstacles()`
- `bool NPC:AutoMovement(float interval, Entity target = NULL)`

I did not add the move trace result return to AutoMovement since it's only returned for one move type, making it useless most of the time. If you have a use case for it, please let me know.

**Comment by DrVrej** [comment] 2021-02-24 01:56
> Added:
> 
> * `float Entity:GetAnimTimeInterval() [CBaseAnimating]`
> 
> 
> * `void NPC:SetMoveVelocity(Vector vel)`
> * `void NPC:UpdateTurnActivity()`
> * `bool NPC:HasObstacles()`
> * `bool NPC:AutoMovement(float interval, Entity target = NULL)`
> 
> I did not add the move trace result return to AutoMovement since it's only returned for one move type, making it useless most of the time. If you have a use case for it, please let me know.

Thank you for taking the time to add these suggestions, NPCs are going to change forever with these new functions and no worries about the trace result, I haven't thought of a use case for it either 👍

**Closed** 2022-04-13 19:20 UTC
