### ISSUE TITLE
Allow tables in Bullet.IgnoreEntity

### ISSUE THREAD

**Issue by homonovus** [Facepunch/garrysmod-requests#1897] opened 2021-07-24 13:07 UTC
### Details
https://wiki.facepunch.com/gmod/Structures/Bullet
Bullet.IgnoreEntity only allows for 1 entity to be ignored during a FireBullets() call.

https://wiki.facepunch.com/gmod/Structures/Trace
TraceLine/TraceHull allows for multiple entities to be used for filtering.

please let us filter more than one ent :)

**Comment by Kefta** [comment] 2021-07-25 02:56
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/641 and https://github.com/Facepunch/garrysmod-requests/issues/969.

**Closed** 2021-07-25 12:27 UTC
