### ISSUE TITLE
Support for Lightmapped_4WayBlend

### ISSUE THREAD

**Issue by Mingooberus** [Facepunch/garrysmod-requests#2268] opened 2024-01-20 15:20 UTC
### Details
Currently the only branches of Source 1 that support/supported four-way blends were those of which were used in Black Mesa and Counter Strike: Global Offensive (before it swapped engine). Four-way blends are textures that allow the blending of four textures specifically for displacements in Hammer. A .vmt would have a header of Lightmapped_4WayBlend with four corresponding $basetexture1-4 sections. 
I understand these "branches" aren't open-source however I don't know the full extent of Rubat and anyone else working on Garry's Mod's knowledge of the engine.
If not possible could we at-least get automatic conversion of these textures to WorldVertexTransition?

**Comment by robotboy655** [comment] 2024-01-20 15:50
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1437

**Closed by robotboy655** 2024-01-20 15:50 UTC
Labels: Duplicate, Shaders
