### ISSUE TITLE
Allow Static Props with bump maps to be vertex lit with -staticproplighting

### ISSUE THREAD

**Issue by bizzclaw** [Facepunch/garrysmod-requests#1615] opened 2020-06-03 01:11 UTC
From the [Advanced Lighting](https://developer.valvesoftware.com/wiki/Advanced_Lighting) page on the valve wiki
> Props that use bump maps or phong materials cannot be vertex-lit. This limitation does not extend to the Counter-Strike: Global Offensive engine branch.

This limitation means we have to choose between bump maps or proper shadows and lighting on static props. My request is that if this limitation is reviewed and potentially worked around if it is something that would be potentially easy to implement. This would allow for much better-looking levels assembled from tile-set models, as well as allowing full building models to be dark on the inside of them, without sacrificing normal map / phong detail.

Thank you.

**Comment by Jaffies** [comment] 2020-06-06 09:40
Duplicate of #1212 
But anyway, this is a real problem what needs to be solved :/

**Comment by bizzclaw** [comment] 2020-06-07 00:49
Ah, I tried searching "-staticproplighting" before posting, but yeah it would be really amazing.

**Closed** 2020-06-07 18:38 UTC
