### ISSUE TITLE
Enable ClientsideModel (C_BaseFlex) to receive projected texture shadows

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/garrysmod-requests#1806] opened 2021-02-19 18:35 UTC
### Details
Enable clientside models to be affected by projected textures, the same way it was enabled on the viewmodel entity using the following code:

```
virtual bool ShouldReceiveProjectedTextures( int flags )
{
	return true;
}
```

### Purpose
This would fix bonemerged clientside models on weapon viewmodels not receiving light from projected textures, such as lamps/other entities using projected textures.

**Comment by robotboy655** [comment] 2021-02-19 19:14
But they already do?
![image](https://user-images.githubusercontent.com/3299036/108550609-77f58600-72f7-11eb-8251-bdf8d6fe566d.png)

concommand.Add( "test_csent", function( ply )
	local plyTr = ply:GetEyeTrace()

	csEnt = ClientsideModel( "models/props_c17/oildrum001_explosive.mdl" )
	csEnt:SetPos( plyTr.HitPos + plyTr.HitNormal * 24 )
	csEnt:Spawn()
end )

**Comment by Gmod4phun** [comment] 2021-02-19 19:51
Alright, tested your code and it works, however setting `SetNoDraw(true)` to hide the model upon creation, and then using `DrawModel()` to draw it in a different context causes it not to be affected by the projected texture. (That is my use-case)  
![modeltest](https://user-images.githubusercontent.com/5991682/108553698-5c887c00-72f3-11eb-940e-551229ee3192.jpg)

At least we established it does indeed work, but not in the way I am using it. This raises a question if this is the intended behaviour or is it a bug?

**Comment by robotboy655** [comment] 2021-02-19 19:54
I think it may be related to https://github.com/Facepunch/garrysmod-issues/issues/3029

I will need to do more testing.

**Comment by Gmod4phun** [comment] 2021-02-19 19:55
Alright. If it helps, I am running the DrawModel inside of PostDrawViewModel, same behaviour in PostDrawOpaque/TranslucentRenderables.

**Comment by LeQuackers** [comment] 2021-02-24 15:09
Might has something to do with this:
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/client/c_baseentity.cpp#L1543-L1544

**Comment by robotboy655** [comment] 2021-02-24 18:39
It's not due to `ShouldReceiveProjectedTextures`.

As I suspected, it's due to the flashlight states simply not being setup for the render operation. The fix I have for Facepunch/garrysmod-issues#3029 (which involves a new function that you give a callback that calls `DrawModel()`, etc ) works here as well, but it creates ugly artifacts when used with IMeshes, which is something I'd rather not ship, but don't really know how to fix either atm.

![image](https://user-images.githubusercontent.com/3299036/109048835-37737f00-76e0-11eb-97e9-5dd8b8ab2d96.png)

You can see the ugly lines on the left model which is an IMesh.

**Comment by LeQuackers** [comment] 2021-02-24 19:00
Interesting. The artifacts look like shadow acne; is there anything related to depth bias in the function you're working on?

**Comment by Gmod4phun** [comment] 2021-02-24 21:16
So basically we are fucked. If I look closely though, I can see the same shadow problem in the edges of the right bomb model, just not as horrible as on the IMesh. I used to see those on regular models under certain conditions, iirc it had something to do with the flashlight texture resolution/depth.

**Comment by LeQuackers** [comment] 2021-02-24 22:57
If you need a quick fix use ```ENTITY:RenderOverride``` or make a custom entity and use ```ents.CreateClientside```.

As for the depth bias theory I can get a pretty similar result if ```mat_depthbias_shadowmap``` is -0.0001 (negative of the default). Hopefully that helps a bit.

```ENTITY:RenderOverride``` example:
```
local test = NULL

local SHOULD_DRAW = false
local function draw(self, flags)
	if SHOULD_DRAW then self:DrawModel(flags) end
end

concommand.Add("github_test", function(ply, com, args)
	local tr = ply:GetEyeTrace()
	local vm = ply:GetViewModel()
	
	test = ClientsideModel("models/props_c17/oildrum001_explosive.mdl")
	test.RenderOverride = draw -- avoids nodraw weirdness
	test:SetModelScale(0.25)
	local i = vm:LookupBone("ValveBiped.square") -- from weapon_pistol
	if i then
		test:FollowBone(vm, i)
		test:SetLocalPos(vector_origin)
		test:SetLocalAngles(angle_zero)
	end
	test:Spawn()
end)

hook.Add("PostDrawViewModel", "test", function(vm, ply, weapon)
	if test:IsValid() then
		SHOULD_DRAW = true
		test:DrawModel()
		SHOULD_DRAW = false
	end
end)
```

```mat_depthbias_shadowmap -0.0001```

![image](https://user-images.githubusercontent.com/16133099/109076260-4c441880-76c8-11eb-832d-c9f7ae4ea841.png)

**Comment by robotboy655** [comment] 2021-03-15 18:18
So in the end the issue is a duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3809

**Closed by robotboy655** 2021-03-15 18:18 UTC

**Comment by robotboy655** [comment] 2023-06-15 18:35
I could not reproduce the weird glitchy rendering so I am releasing this.

https://wiki.facepunch.com/gmod/render.RenderFlashlights

This function (example included) solves the issue.

**Comment by Gmod4phun** [comment] 2023-06-15 22:14
Nice to see this still being worked on :)
