### ISSUE TITLE
Add GetMaxArmor and SetMaxArmor func.

### ISSUE THREAD

**Issue by FalseGM** [Facepunch/garrysmod-requests#1610] opened 2020-05-30 22:57 UTC
This will be a necessary feature, given that most of the servers are Roleplay mode. This option allows you to better set the balance.

**Comment by CornerPin** [comment] 2020-05-30 23:41
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/153

**Closed** 2020-05-31 10:35 UTC
