### ISSUE TITLE
Requests multilingual support of HUD

### ISSUE THREAD

**Issue by IssacKleiner** [Facepunch/garrysmod-requests#1194] opened 2018-07-17 09:40 UTC
I want HUD to correspond to various languages. (For example, such as Japanese or Chinese) actually Half-Life 2 in so multi-language support

**Comment by robotboy655** [comment] 2020-01-30 18:32
This is basically fulfilled by/duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4110

**Closed by robotboy655** 2020-01-30 18:32 UTC
