### ISSUE TITLE
BaseAnimatingOverlay:RemoveLayer() and other BaseAnimatingOverlay missing functions

### ISSUE THREAD

**Issue by Dragoteryx** [Facepunch/garrysmod-requests#1359] opened 2019-06-23 20:22 UTC
I noticed that for some reason BaseAnimatingOverlay:AddGestureSequence() doesn't actually play the whole animation, so I was trying to use AddLayeredSequence, but right now the only way to remove layers is to either use AddGestureSequence with the second argument set to true or call RemoveGesture/RemoveAllGestures, but there is no way to remove a specific layer. 

https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/server/BaseAnimatingOverlay.cpp
At line 1079 there is a function called RemoveLayer that wasn't added to the Lua API, as well as a few more functions that could be very useful.

I know #1127 already requested to add those functions to the Lua API, but since it's from last year I suppose it was ignored, so I'm making a new request.

**Comment by Kefta** [comment] 2019-06-23 20:27
Duplicate requests don't make things get noticed quicker.

**Comment by robotboy655** [comment] 2019-06-24 18:44
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1127

**Closed by robotboy655** 2019-06-24 18:44 UTC
