### ISSUE TITLE
Add a line thickness parameter to surface.DrawLine?

### ISSUE THREAD

**Issue by Palexite** [Facepunch/garrysmod-requests#2543] opened 2024-11-25 06:10 UTC
I want to be able to do some visuals by doing procedural outlining effects of the user interface, but by default the lines are extremely narrow and miniscule. I'm surprised there is not a line thickness parameter for simply a line.

**Comment by robotboy655** [comment] 2024-11-25 11:53
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1679

**Closed by robotboy655** 2024-11-25 11:53 UTC
