### ISSUE TITLE
Add SetDepthFilter() and SetDepthRes() to ProjectedTexture() object

### ISSUE THREAD

**Issue by Kidnation** [Facepunch/garrysmod-requests#1258] opened 2018-12-27 03:09 UTC
The ability to set a individual filter and depth resolution to ProjectedTexture() objects sounds nice, instead of having it constrained to r_projected_filter and r_flashlightdepthres, which can be used as default values instead.

**Comment by xoticdev** [comment] 2020-05-07 07:05
I agree!!!

**Comment by robotboy655** [comment] 2021-03-15 19:46
Added ProjectedTexture.SetShadowSlopeScaleDepthBias, ProjectedTexture.SetShadowDepthBias, ProjectedTexture.SetShadowFilter
(Get methods included)

SetDepthRes is not really possible with how the system is set up internally. I'd consider that one point to be duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1726

**Closed by robotboy655** 2021-03-15 19:46 UTC
