### ISSUE TITLE
Make Player:EmitSound respond to SuppressHostEvents in weapon hooks

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1214] opened 2018-09-21 09:08 UTC
Playing sounds on the player instead of the weapon entity is extremely common in existing Lua code and causes sounds to be played multiple times. Other events already respond to SuppressHostEvents in weapon hooks (player/weapon netvar changes, weapon sounds).

**Comment by robotboy655** [comment] 2018-09-22 05:12
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2651

**Closed by robotboy655** 2018-09-22 05:12 UTC

**Comment by robotboy655** [comment] 2018-09-22 05:13
Thing is about playing sounds on the Owner and not the weapon itself, this IS how it actually works when you call the function on a Weapon object, the difference is that the PAS filter gets the prediction rules treatment.

**Comment by Jvs34** [comment] 2018-09-22 09:05
I think it'd be nice if we were able to pass a custom filter to ent:EmitSound because of that, had to make my own net messages on an entity base of mine to get around that.
