### ISSUE TITLE
In regards to CSM for maps in Garry's Mod

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1519] opened 2020-02-29 21:08 UTC
I recently came across this in a discord server for source engine. I believe this commit could help for getting CSM added into garry's mod. I'm linking the commit itself so that you guys get a list of all the file changes made when they added this into the repo. So far somebody else is implementing this into their own source mod aswell so I feel it would be both possible and great if facepunch also were able to do the same.

https://github.com/quiverteam/Engine/commit/a0db08ceb862a6595d3c675f993fa43d0bc77308?diff=unified#

**Comment by robotboy655** [comment] 2020-03-01 01:19
Duplicate of your own issue https://github.com/Facepunch/garrysmod-requests/issues/1474

Just comment on an existing issue, don't open a new one.

**Closed by robotboy655** 2020-03-01 01:19 UTC

**Comment by VaasKahnGrim** [comment] 2020-03-01 10:55
> Duplicate of your own issue #1474
> 
> Just comment on an existing issue, don't open a new one.

I would but its not like you'll ever read them it seems

**Comment by robotboy655** [comment] 2020-03-01 23:11
I don't know how many times do I have to repeat - I read every single github comment on these repos.

**Comment by VaasKahnGrim** [comment] 2020-03-01 23:29
I'm sorry but it really doesn't feel like it half the time, alot of shit has gone uncommented on for years

**Comment by robotboy655** [comment] 2020-03-02 00:41
Because there's one of me, and hundreds of you.

**Comment by VaasKahnGrim** [comment] 2020-03-02 00:49
3. You, Willox and Garry.
