### ISSUE TITLE
Fix '_restart' command

### ISSUE THREAD

**Issue by Ry13y04** [Facepunch/garrysmod-requests#1396] opened 2019-08-25 16:26 UTC
In other Source games, like HL2, the _restart command would restart the game/engine. In Garry's Mod, the command crashes the game.

**Comment by neico** [comment] 2019-08-25 17:08
Wrong repo, and duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2406

**Closed** 2019-08-25 18:08 UTC
