### ISSUE TITLE
Include CS:GO's vaudio_celt

### ISSUE THREAD

**Issue by opeik** [Facepunch/garrysmod-requests#547] opened 2015-07-26 13:46 UTC
As you probably already know, CS:GO made CELT it's default audio codec. It would be great if you could include the codec into Garry's Mod so servers can toggle what they want to use via sv_voicecodec.

**Comment by Gliby** [comment] 2015-07-28 01:04
Yes please!

**Comment by TylerB260** [comment] 2015-08-19 16:30
please

**Comment by GlenAnderson** [comment] 2015-08-22 01:43
Garry's Mod NEEDS this. Bring some life to the project guys! +1000

This has been put off WAY too long :(

**Comment by meatspace** [comment] 2015-12-12 21:39
yes pls

**Comment by robotboy655** [comment] 2016-02-28 22:12
Closing as duplicate of #479 / #647

**Closed by robotboy655** 2016-02-28 22:12 UTC
