### ISSUE TITLE
Function to get connecting players or at least the count

### ISSUE THREAD

**Issue by TheNickSkater** [Facepunch/garrysmod-requests#1612] opened 2020-06-01 10:52 UTC
I actually am a bit upset that this is not a function that exists (or I dont know of?).

It would be very nice to have a function that gives you either the Players that are connecting right now (for example with the same parameters as the player_connect gamevent) or at least a function that gives you the count of Players that are currently still connecting and not fetched by "player.GetAll()".

I hope this will make it somewhat :).

**Comment by viral32111** [comment] 2020-06-01 13:10
If you want a hacky solution, then just add players to a key-value table when `player_connect` is fired then remove them when `player_disconnect` and `PlayerInitialSpawn` is fired. I suppose if a function was implemented, this is probably how it would be done too.

But I could've sworn there was a native way to get players in `TEAM_CONNECTING` (`Joining/Connecting`) already?

**Comment by robotboy655** [comment] 2020-06-01 13:30
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/843

**Closed by robotboy655** 2020-06-01 13:30 UTC
Labels: duplicate

**Comment by TheNickSkater** [comment] 2020-06-01 15:20
> If you want a hacky solution, then just add players to a key-value table when `player_connect` is fired then remove them when `player_disconnect` and `PlayerInitialSpawn` is fired. I suppose if a function was implemented, this is probably how it would be done too.
> 
> But I could've sworn there was a native way to get players in `TEAM_CONNECTING` (`Joining/Connecting`) already? Does [`team.GetPlayers( TEAM_CONNECTING )`](https://wiki.facepunch.com/gmod/team.GetPlayers) or [`team.NumPlayers( TEAM_CONNECTING )`](https://wiki.facepunch.com/gmod/team.NumPlayers) return anything?

Sadly the team does not return any players :/

Also the Duplicate that was set on this is from 2016.. 4 Years and nothing has changed.. well nice
