### ISSUE TITLE
Restore Use SFX from GM12 and Below as Client Convar

### ISSUE THREAD

**Issue by SupahMario** [Facepunch/garrysmod-requests#1456] opened 2019-11-10 23:09 UTC
Ever since the dawn of time, the game played a sound effect whenever you used an object (+use). However, when Garry's Mod 13 was rolled out, that feature was removed from the game. I request that this is restored, and the client can toggle it only for itself. The gamemode may also be able to disable it or enable it for certain players, ignoring the client's preference.

This can also go well with the newly added gmod_suit command (which is available for branches other than prerelease)

**Comment by robotboy655** [comment] 2019-11-10 23:34
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1447

**Closed by robotboy655** 2019-11-10 23:34 UTC
