### ISSUE TITLE
Porting Newer Source Game Maps to gmod

### ISSUE THREAD

**Issue by jbuug** [Facepunch/garrysmod-requests#905] opened 2017-02-06 12:35 UTC
i believe that games such as ("CS-GO, left for dead-2, PORTAL 2, ETC")

We  should have a way to make these maps in a playable state for Garry's mod.
at-least try to put it under testing.

**Comment by robotboy655** [comment] 2017-02-06 12:45
Duplicate of #271

**Closed by robotboy655** 2017-02-06 12:45 UTC
