### ISSUE TITLE
Function to pull a player's flashlight entity

### ISSUE THREAD

**Issue by Vuthakral** [Facepunch/garrysmod-requests#1982] opened 2022-06-23 20:24 UTC
### Details
Currently, I do not believe there is a non-convoluted (or any reliable) method of getting the projected texture entity of the local player's flashlight. I'm personally in need of access to modifying the flashlight's values [to set a proper NearZ for my full-body first person so flashlight doesn't "see" the FP body](https://i.imgur.com/BvAMz5G.jpeg), however I can think of many other things people could benefit from by having direct access to the player's flashlight entity.

A note, the standard flashlight is already hard-tied to many convars which are already locked behind `sv_cheats`, which has resulted in so many custom flashlight systems written on the workshop I can't possibly count them all. I try not to presume too much, but I imagine untying the flashlight from these convars and instead applying default values & allowing the flashlight to be called in lua would be a lot better given the nature of Garry's Mod, being able to modify the player's flashlight like any other projected texture in lua could open the door to a lot of possibilities for gamemodes, weapons, and etc.

**Comment by robotboy655** [comment] 2022-06-24 10:15
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1420

**Closed by robotboy655** 2022-06-24 10:15 UTC
