### ISSUE TITLE
Add lua function to create textures

### ISSUE THREAD

**Issue by MagnumMacKivler** [Facepunch/garrysmod-requests#1749] opened 2020-11-11 23:34 UTC
As discussed in [Issue #4727](https://github.com/Facepunch/garrysmod-issues/issues/4727), a function to import a PNG/JPG file into the game as a texture, similar to Global.Material() but without creating an actual material to go with it.

**Comment by thegrb93** [comment] 2020-11-12 00:29
Doesn't ITexture need a material referencing it or else it gets destroyed?

**Comment by robotboy655** [comment] 2020-11-12 00:36
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/605

Thank you for using the search feature!

**Closed by robotboy655** 2020-11-12 00:36 UTC
