### ISSUE TITLE
Utility to display custom status via Discord RPC

### ISSUE THREAD

**Issue by Rubik7711** [Facepunch/garrysmod-requests#2090] opened 2023-05-24 14:37 UTC
### Details
Server-side utility to provide custom Discord activity status via RPC. 

util.SetRPCStatus(ply,activity[String],state[String],timeout[optional int])

![image](https://github.com/Facepunch/garrysmod-requests/assets/25591967/3d6e436b-69b5-4bd0-8ae7-29bee496928b)

**Comment by robotboy655** [comment] 2023-05-24 14:45
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1041

**Closed by robotboy655** 2023-05-24 14:45 UTC
