### ISSUE TITLE
Bind CBaseAnimating->IsActivityFinished and IsSequenceFinished

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#704] opened 2016-04-05 00:41 UTC
This would tell whenever the sequence last played is over instead of having a NetworkVar mange it with CurTime comparisons, since GetSequence/GetActivity will always return the last used sequence, regardless if it's done playing. It works on players, viewmodels, and NPCs!

**Comment by Kefta** [comment] 2016-04-19 01:17
Or, please add DEFINE_FIELD( m_bSequenceFinished, FIELD_BOOLEAN ) to c_baseanimating and this can be solved with GetInternalVariable instead.

**Comment by robotboy655** [comment] 2020-04-15 15:12
Added Entity.IsSequenceFinished
I do not see much point in adding `IsActivityFinished` as it is basically duplicate of `IsSequenceFinished`.

**Closed by robotboy655** 2020-04-15 15:12 UTC
