### ISSUE TITLE
Shaders && Parallax Mapping: Source included from Alien Swarm... 

### ISSUE THREAD

**Issue by xoticdev** [Facepunch/garrysmod-requests#1755] opened 2020-11-26 00:43 UTC
Hey! So... Before I go into detail... If you haven't already checkout some of my issues I posted, I hope that you [do](https://github.com/Facepunch/garrysmod-issues/issues/4713).

Long story short, Parallax Mapping is probably one of the best ways to go about adding finer detail to a map/texture you have in the game. I can explain what it means, but It's a fancy way of suggesting we update our shaders. Why? Well if you take a look from my links below, you'll see how:

Here is a github from Alien Swarm. They have parallaxmapping source https://github.com/NicolasDe/AlienSwarm/tree/c5a2d3fa853c726d040032ff2c7b90c8ed8d5d84/src/materialsystem/stdshaders

Here is Valve WIKI Talking about Parallax Mapping
https://developer.valvesoftware.com/wiki/Parallax_mapping

Here is video of a demonstration of what's possible
https://www.youtube.com/watch?v=PFHD2le0PoM

As it describes and showcases, it is indeed possible with DX9 (although probably resource heavy, nice to have though). 
So if you do decide on making this happen. I want to be notified about it. I'm always seeking to further my knowledge of source engine. I think this is a pretty great thing to have. I wish I could just include it myself but... Yeah.

**Comment by Kefta** [comment] 2020-11-26 01:11
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/972.

**Closed by Kefta** 2020-11-26 01:11 UTC
