### ISSUE TITLE
Disable "retry" command in SP

### ISSUE THREAD

**Issue by gonzalologorg** [Facepunch/garrysmod-requests#1083] opened 2018-01-19 18:28 UTC
Is there a way retry command can get disabled by being running in singleplayer mode or self hosted?
Actually retry doesn't work if you call it inside srcds or in menu state since you're not connected anywhere

So what do you think guys

**Comment by Kefta** [comment] 2018-01-19 18:48
Why?

**Comment by gonzalologorg** [comment] 2018-01-19 19:33
It freezes the game inside "Sending client info" until you have to close it via task manager

**Comment by robotboy655** [comment] 2018-01-19 19:53
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2713

**Closed by robotboy655** 2018-01-19 19:53 UTC
