### ISSUE TITLE
Make AddGesture/AddGestureSequence/AddLayeredSequence available shared

### ISSUE THREAD

**Issue by Kinyom** [Facepunch/garrysmod-requests#1254] opened 2018-12-23 00:53 UTC
These functions are currently only available serverside. If they could be used clientside as well, this would allow for prediction of blended/layered sequences for non-player entities; I'm working with some viewmodels that use them, and can't use their animations because the functions aren't shared.

**Comment by Kefta** [comment] 2018-12-23 02:31
Kind of a duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1252

**Comment by Kinyom** [comment] 2019-02-27 19:14
One other argument for this, Counter Strike: Source's player animation system uses these layer-adding functions to add a "holding weapon" animation on top of their base "run" animation. So if someone would want to use them in their gamemode, they'd need these functions to add that correctly. If we have similar functions implemented shared for the flex system, I'm not too sure of anything that'd make this difficult to add.

**Closed** 2020-02-10 16:53 UTC
