### ISSUE TITLE
GetModelMeshes (code provided)

### ISSUE THREAD

**Issue by Ramalayha** [Facepunch/garrysmod-requests#1216] opened 2018-09-25 15:33 UTC
[Code](https://pastebin.com/9wfu7xWn)

GetModelMeshes(model, lod = 0, bodygroupmask = 0)

Gets the material and triangles for each of the models meshes (body, face, eye, teeth etc)

returns a table of entries formatted like this
`{
    material = "materialname",
    triangles = {}
}`

where material is the material used for that specific mesh and triangles is a table of [MeshVertex](http://wiki.garrysmod.com/page/Structures/MeshVertex)es ready for use with [IMesh:BuildFromTriangles](http://wiki.garrysmod.com/page/IMesh/BuildFromTriangles)

each vertex also has an additional entry called "weights" which is a table of entries formatted like this `{bone = boneid, weight = floatweight}`

The bodygroup mask can be generated based on an entity's bodymask like so [GetBodygroupMask](https://pastebin.com/3sjn0SM9)

**Comment by robotboy655** [comment] 2018-09-25 15:48
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/84

**Closed by robotboy655** 2018-09-25 15:48 UTC

**Comment by rickomax** [comment] 2019-03-20 23:25
Any chance of getting this implemented?

**Comment by thegrb93** [comment] 2019-03-21 00:16
The implementation is right there in OP, but oh well.

**Comment by rickomax** [comment] 2019-03-21 00:18
I know, but it's not on Garrys Mod yet

**Comment by shadowscion** [comment] 2020-07-19 17:14
@Ramalayha The GetBodygroupMask function you provided only seems to work if the bodygroups are structured a certain way (no sublists).

**Comment by Ramalayha** [comment] 2020-07-21 12:09
The function only accepts a mask so I'm not sure what can be done about that.
