### ISSUE TITLE
support for flow maps

### ISSUE THREAD

**Issue by Combine900** [Facepunch/garrysmod-requests#1430] opened 2019-10-09 22:18 UTC
can we may add support for flow maps from l4d2?

https://developer.valvesoftware.com/wiki/Water_(shader)#Flowing_water

**Comment by robotboy655** [comment] 2019-10-09 22:26
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1162

**Closed by robotboy655** 2019-10-09 22:26 UTC
