### ISSUE TITLE
Raising the 128 surface property limit to a bigger number 

### ISSUE THREAD

**Issue by Akis-02** [Facepunch/garrysmod-requests#1591] opened 2020-05-07 15:04 UTC
tittle is self explanatory, i have no idea what to put here

**Comment by Kefta** [comment] 2020-05-07 15:19
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3331. You can see why the issue hasn't been completed in the thread.

**Closed** 2020-05-07 16:02 UTC
