### ISSUE TITLE
Bind NPC:NPC_TranslateActivity(eNewActivity) to Lua

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-requests#2212] opened 2023-11-15 22:24 UTC
### Details
Very widely used function in Source engine, almost every default HL2 NPC manipulates this function one way or another. Here is how it would work in Lua:
- returning nothing should allow the default C++ code to run
- returning a number (activity) should override the C++ code

Link: https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_basenpc.h#L928

**NOTE: THIS IS DIFFERENT THEN WEAPON TRANSLATE ACTIVITY! THIS IS FOR THE NPC ITSELF REGARDLESS IF THEY HAVE A WEAPON OR NOT!**

**Comment by robotboy655** [comment] 2023-11-16 15:09
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1867

**Comment by robotboy655** [comment] 2023-11-16 16:25
Added as `ENT:TranslateActivity( act )`

**Closed by robotboy655** 2023-11-16 16:25 UTC
