### ISSUE TITLE
Allow the use of gesture functions for the entities on client realm

### ISSUE THREAD

**Issue by Shakychn** [Facepunch/garrysmod-requests#2258] opened 2024-01-06 06:14 UTC
It would be quite in handy, since it would really be a good feature for viewmodels or client entities, which require some kind of gesture for some actions

**Comment by robotboy655** [comment] 2024-01-11 14:04
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1723

**Closed by robotboy655** 2024-01-11 14:04 UTC
